### ISSUE TITLE
SLaM unable to access HL to test bug fix

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1013]
Initially when he clicked on the HL button in epJS he got a blank screen.

I looked and HL seemed to be up and working so send him the link to staging: https://staging.healthlocker.uk/

When he tried going here directly, after around 40 seconds he gets the following screen:

![image001](https://user-images.githubusercontent.com/24604903/29659071-f6ee1ad4-88b4-11e7-9dbc-cbb69cdf0a08.jpg)

Can someone look at this ASAP

**Comment by reddog** [comment]
@katyedwards Is the staging site working for you?  It's working from here in the Mindwave office.

If it works for you and me, could this be a SLaM internal firewall issue and not a dev issue at all?

**Comment by reddog** [comment]
It works on a (newer version of) Internet Explorer from the Mindwave office.

**Comment by katyedwards** [comment]
@reddog  works fine for me, but I can't access the clinician interface

**Comment by katyedwards** [comment]
I'll push it back to SLaM and will ask them to check the firewall

**Comment by reddog** [comment]
The error shown in this issue is slightly different from the previous internal SLaM firewall issues, see:

![image](https://user-images.githubusercontent.com/151362/29659930-b0103338-88b7-11e7-8bfd-485c668d193b.png)

So *maybe* it's actually not an internal SLaM firewall issue?

**Comment by RobStallion** [comment]
Who are you logged in as when you are getting that error?

Can you list all the steps to replicate please?

**Comment by katyedwards** [comment]
@RobStallion 
He logged into ePJS as himself - James Roberts 
Clicked the HL icon in ePJS to load caseload and got a blank screen

Then tried just going directly to https://staging.healthlocker.uk/ in his browser and after 40 seconds got the page can't be displayed message

Does that give enough info?

**Comment by reddog** [comment]
@katyedwards Could there be an application issue with regard to some sort of information stored on his computer (some cookie that's used by the app maybe)?

Can you ask James to access https://staging.healthlocker.uk/ from another computer within his office that hasn't previously been used for Healthlocker access?

**Comment by RobStallion** [comment]
@katyedwards Thanks for that. Unfortunately I cannot access the site the same was as James. He could also try using the site in a private browser session to check if he has the same issue. 

@reddog could you list the steps that you took to get the error you posted above? Also did the error occur on other browsers as well or just while you were on IE?

**Comment by katbow** [comment]
Are other sites loading okay for him on the same browser?

**Comment by reddog** [comment]
@RobStallion The error posted at https://github.com/healthlocker/healthlocker/issues/1013#issuecomment-324585007 was previously raised and related entirely to internal SLaM firewall issues.  The error there is different to that shown now.

**Comment by reddog** [comment]
Further feedback from James:

Tested on a computer that he thinks hasn't used used to access HL from previously.  When accessing https://staging.healthlocker.uk/ directly he gets the following error:

![image003](https://user-images.githubusercontent.com/151362/29663544-8a594e8e-88c3-11e7-9ba3-cd8e513500fb.jpg)

When accessing HL from within ePJS on that same computer he gets the following error:

![image](https://user-images.githubusercontent.com/151362/29663579-b180b998-88c3-11e7-9036-53c695f5ed60.png)

This second screenshot is *similar* to that previously displayed when the issue was to do with SLaM's internal firewall.  However, an internal, private IP of 192.168.150.7 is shown, and not the external IP address.

This private IP address is referenced here https://github.com/healthlocker/healthlocker/issues/879#issuecomment-312006340  The staging site has worked after this point.

@RobStallion & @katbow Can you confirm if the private IP address (listed above) is used anywhere in your deployment process?  Should that actually be the public IP address?

**Comment by RobStallion** [comment]
I have not been able to replicate any of the errors posted here so far. I have used chrome and IE but have had no problems.

@reddog, just to be clear, is issue you posted [here](https://github.com/healthlocker/healthlocker/issues/1013#issuecomment-324585007) still a problem or was it something on slam's end?

With regards to your question [here](https://github.com/healthlocker/healthlocker/issues/1013#issuecomment-324604140), I can see that IP address in an environment variable on the azure staging server but I cannot see anywhere it is used. Also the Azure staging server is not on that IP address. It is at 51.140.86.5. If you type that IP address into your url bar it will take you to the [staging site](https://staging.healthlocker.uk/).

**Comment by reddog** [comment]
@RobStallion The screenshot https://github.com/healthlocker/healthlocker/issues/1013#issuecomment-324585007 was from an internal SLaM firewall issue.

The difference I was highlighting was that although that issue was indeed a SLaM firewall issue, the external IP address of the staging site was correctly shown.

In the second of the two new failure screenshots, it is not the external IP address that's shown but the private (local) IP address of the server.  There are private subnet reasons as to why accessing from the server's private IP address wouldn't work.

It seems from Nelson's comment here https://github.com/healthlocker/healthlocker/issues/879#issuecomment-312006340 that the private IP address of the staging server is indeed 192.168.150.7

51.140.86.5 is the external or public IP address.

You have found the private IP address in an environment setting on the server?  What is that setting?  Should that maybe be set to the external IP address (I have no idea without knowing what the environment setting is).

**Comment by katyedwards** [comment]
Closing this as we have heard no more from SLaM and they seem to be progressing with their testing.
