### ISSUE TITLE
Registration Internal server error

### ISSUE THREAD

**Issue by nelsonic** [healthlocker/healthlocker#107]
when attempting to register on https://healthlocker.herokuapp.com click/tap on the "burger" menu and then on Sign up/Log In
![image](https://cloud.githubusercontent.com/assets/194400/23129994/a82246c4-f77c-11e6-93cd-d719b659d3df.png)
(_which does not work without JS, but that's another issue..._)

The form looks ok: 
![image](https://cloud.githubusercontent.com/assets/194400/23130026/d05fb22a-f77c-11e6-96e4-8d58ffcfda08.png)
but when I enter data and submit it ...

I see:
![image](https://cloud.githubusercontent.com/assets/194400/23129983/98a4c5be-f77c-11e6-8acc-8588ec9c5022.png)

@katbow Is this fixed in one of the branches?

**Comment by katbow** [comment]
hmm that's odd. I am not getting that locally. Also I just went to https://healthlocker.herokuapp.com/ and I have an internal server error for the homepage as well, or any other route that I type in.

**Comment by katbow** [comment]
Ahh, I had a cookie set so nothing was showing up for me. So I removed that and then I was able to go to sign up. I think it is putting current user in the session too early - it was there after I went through the first form and I got the internal server error then.

Looking more at this now to see when the session is being set. I think it might be already fixed in the coping-strategies branch, but I'll verify.

**Comment by katbow** [comment]
Okay I tried it out on the heroku deployment for that branch PR and it works there 👍

**Comment by nelsonic** [comment]
@katbow thanks for investigating and clarifying. 👍

**Comment by katbow** [comment]
@nelsonic I looked at it again because there were more errors after the merge of those branches. I needed to run `mix ecto.migrate` on the app. I am wondering if there's a way to run this automatically when the production app is built @tonydaly. If not at least now I know to do that when there are changes to the db 😄

**Comment by katbow** [comment]
@nelsonic can this be closed now?

**Comment by nelsonic** [comment]
@katbow yes, thanks!
