### ISSUE TITLE
From PEN Testing: The application was vulnerable to a persistent Cross-site Scripting (XSS) attack.

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1074]
### **From PEN Testing:**

**Overview:**
The application was vulnerable to a persistent Cross-site Scripting (XSS) attack.
Stored or persistent XSS arises when user-provided JavaScript code is stored in the
backend database.
The application allowed users to update their database entries in multiple areas of the
application, such as the setting of goals or copying strategies. This information was
stored and would be displayed to other users of the site, such as the people
“connected” to the users and also staff.
The application did not perform data validation and as such scripting code, which
would execute in other users' browsers, could be entered and stored in the application.
This could be leveraged to steal other users' data such as session cookies. In the
context of the application, this might enable a malicious user to steal sessions of
“connected” users or staff.

**Recommendations:**
Full and complete validation should be performed on all client supplied or otherwise
tainted data, and suitable encoding applied where appropriate. These validation
checks must be performed on the server side as well, where malicious users cannot
tamper with the validation routines. All data should be suitably encoded before being
sent to the user's browser. For further information about XSS, please see:
https://www.owasp.org/index.php/Cross-site_Scripting_
Ideally, all user-supplied data should be subjected to such input-validation and
encoding before being stored in the database. For more information please refer to:
https://www.owasp.org/index.php/XSS_(Cross_Site_Scripting)_Prevention_Cheat_Sheet

**Comment by katyedwards** [comment]
Extract from PEN testing report emailed to @katbow and @iteles today.

**Comment by katyedwards** [comment]
Please can you time estimate implementing these data validation checks.  Thanks!

**Comment by reddog** [comment]
@katbow Thanks for the time estimate.  Can you give us an idea of where the 1 day time would be spent?  What has to be done to fix this?

**Comment by katbow** [comment]
Update for this work so far: [Phoenix.HTML](https://hexdocs.pm/phoenix_html/Phoenix.HTML.html) assumes data output is not safe. 

eg. `<%= raw "<img src='some_image.jpg' class='w4 h4'/>" %>` will display the image because raw tags it as safe. Without it, it displays as &ltimg src='http://www.cats.org.uk/uploads/images/featurebox_sidebar_kids/grief-and-loss.jpg' class='w4 h4'/&gt.

The cases where this is happening is when using markdown, as it's job is to produce HTML from markdown & HTML.

**Comment by reddog** [comment]
@katbow Thanks for your update on progress so far.  I don't know if you saw my comment above.  Are you able to give an idea of what the steps are for this one day task?

**Comment by katbow** [comment]
It's 1 day because I need time to identify the problem (since phoenix normally does this by default, but I think I have done this now with the markdown posted above). Since it is site wide, I will need enough time to go through the app and ensure that it is fixed and tested in all areas where it needs to be fixed.

**Comment by katbow** [comment]
@katyedwards since this is a markdown problem I am wondering if we can also reconsider where this is being used and remove in places where it is not longer necessary.

In goals for example, I believe it was originally included before goal steps were added in. In that case, a user could add steps of their own by using the `*` symbol.

Since this is a rather hidden feature, that users can format how the text outputs by how they input it with markdown, and also that many users will not even know markdown, I would propose removing it in many of the cases for user input. I'll give a list on slack of all the places this is used where the user provides input and from there we can see where this is necessary, if anywhere.

**Comment by katyedwards** [comment]
Thanks @katbow 

Agreed.  I think the only place we _need_ it is on posts/ tips input, but as you say that is restricted to admin so should only pose a very limited security risk.
We can live without the others.

My feeling on this is that we need to draw a line under this (much extended) phase of the project.

If it is quick to implement to remove markdown functionality from everywhere except posts restricted to admin, that is a good solution now to respond to the PEN testing report.
If the trust want a different solution, we can look at this in the next phase.

**Comment by reddog** [comment]
@katbow Thanks for your update.

Would something like https://github.com/rrrene/html_sanitize_ex be useful?  Given that the `Phoenix.HTML` routines you mention in https://github.com/healthlocker/healthlocker/issues/1074#issuecomment-331171375 might remove all formatting (including removing Mardown formatting), by using `html_sanitize_ex` we could specify which tags should be kept (eg <b>, etc.)

**Comment by katbow** [comment]
I was looking at that as well, but the reason I proposed removing the markdown is because:

* quick solution that will allow `Phoenix.HTML` to automatically encode
* Markdown is not explained as an option to users anywhere, so *many* users will not even realise it's a possibility, except perhaps through trial & error. If we had a user interface where the average user could use markdown for formatter (e.g. like on GitHub comments) then it would make more sense to keep.
* Most of the sections where it was used (besides diary) would be 1-2 sentence inputs, eg. a goal wouldn't likely be paragraphs long. So even if a user *does* know how to use markdown, it's not really useful in the places it was used. 

I think that library is a great solution for keep safe sections that would make good use of markdown, and perhaps when there is something to let the user know how to use it, but right now I think removing it completely from those sections is the best option due to the points above.

**Comment by katyedwards** [comment]
@reddog I don't know how to test this - are you able to?!

**Comment by reddog** [comment]
@katbow Are you able to give us an idea of how you tested the fix?  @katyedwards could then do the same and see the results herself or modify to suit (I'll be able to test if Katy's not available).

**Comment by katbow** [comment]
You can try inputting a simple script into any of the fields we removed markdown from.

Something like: `<script>alert(document.cookie);</script>`. Before, this would cause a pop up to show on the page with the output, with the pop up displaying what looks like random characters (the cookie). This is because it makes the HTML you entered part of the HTML of the page. Now it should display as text, which means it's not part of the page HTML and the alert can't fire. 

I'm not sure what more intensive testing was done by SLaM but this is a simple check before passing it on.

**Comment by katyedwards** [comment]
Have done as @katbow suggests above and indeed, nothing happened, it just added the string as text so I'll close this.  Thanks!
