### ISSUE TITLE
App start/stop/reload script to auto-start/stop app when server brought up/down

### ISSUE THREAD

**Issue by reddog** [healthlocker/healthlocker#1077]
At the moment, HealthLocker requires *manual* intervention in order to start it.

A script should be written to bring it up/down as the server is brought up/down.

**Comment by katbow** [comment]
working on a spike for this atm. time estimate is for the spike **only** for  now.

**Comment by katbow** [comment]
Some useful resources/notes so far:

* [Automate elixir deployment with distillery & edeliver](https://www.digitalocean.com/community/tutorials/how-to-automate-elixir-phoenix-deployment-with-distillery-and-edeliver-on-ubuntu-16-04)
  * the end of the tutorial should result in a single command which builds, deploys, and starts the application in a *single* environment, and deploys the new release without downtime
  * Need to consider how we can use this for both staging & production in cases where the server reboots (since the edeliver config needs to be changed each time for deploying to production and I couldn't find out yet how to have different build_hosts in the config, or if that is even necessary). [Another resource for edeliver `script/deploy`](http://blog.plataformatec.com.br/2016/06/deploying-elixir-applications-with-edeliver/)

**Comment by reddog** [comment]
Replaced by https://github.com/healthlocker/healthlocker/issues/1148
