### ISSUE TITLE
HL Live Stopped - degradation of performance on ePJS

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1078]
SLaM contacted us to say that they had identified a degradation in performance on ePJS and when they investigated ePJS seemed to be taking a lot of hits from HL.

Requested we stop our testing or whatever we're doing until tomorrow morning when the clinical systems team will be back in.

HL live has been stopped until we can investigate in the morning.

**Comment by katbow** [comment]
Can verify this has been stopped for HL live 

![image](https://user-images.githubusercontent.com/1287388/30603582-e2e98784-9d5f-11e7-8a9f-1bda3730288c.png)

**Comment by reddog** [comment]
@katbow Made a good point that, regardless of what HealthLocker night or might not be doing, we *only* access an ePJS **extract** database, and not the *regular* ePJS database.

If the two databases are on the same machine and if HealthLocker is producing excess load then maybe this is an issue.

@katbow When you started HL from the console (with incorrect ePJS extract database login details, during our access checks) we saw lots of connection attempts to the ePJS extract database. Do we know why that is?

**Comment by reddog** [comment]
@katbow I have further information from SLaM's ePJS database admin team - heavy loading of the ePJS **extract** database **will** impact the *regular* ePJS database (and hence the regular ePJS system).  I have asked if there is an monitoring in place on either the database server as a whole or the extract database in order to see if actions of HealthLocker are unexpectedly loading the server.

From a HealthLocker side, can you please provide some information on what HL does with regard to ePJS in terms of when it starts up, ie HealthLocker app is brought app but no users sign in.  During testing yesterday we saw a lot of (failed, because the database authentication credentials were incorrect) traffic to ePJS as the app was brought up (and hence before any usage of the web site, ePJS-wise or otherwise).

**Comment by katbow** [comment]
> ie HealthLocker app is brought app but no users sign in. 
@reddog can you clarify this? No users signed in to where?

If the credentials are incorrect or there are missing dependencies, when the app is brought up it will attempt to connect. This will happen a certain number of times/sec and will stop. I am not sure of the how many attempts occur before stopping.

**Comment by reddog** [comment]
@katbow Thanks for that.

Is there a way of checking how many connection attempts are made?  We saw a lot scroll by in just a few seconds.

With regard to "HealthLocker app is brought up but no users signed in" what I was meaning was;

what is the sum total of ePJS access from HealthLocker if the app is just brought up, nothing else happens, no users access the website, no one logs in, etc.  With regard to the ePJS connection, what will HealthLocker *do* during the start up and sit-there-and-wait (whilst waiting for a user to access the website)?

**Comment by katbow** [comment]
It's something that's predefined by phoenix/ecto. I will need to check if there is a specific value for this/how to find it.

It should be the equivalent of what we did with sqlcmd. As in, log in with correct credentials and connect to the database. It will only try to interact with the MSSQL database when using a feature that accesses it eg. trying to connect to epjs as a carer or service user, clinician looking at their caseload, etc.

**Comment by reddog** [comment]
@katbow Okay, thanks for that. 

So, to confirm, our current understanding is that this is what happens when HealthLocker is started:

**Correct ePJS database connection details**

1.  an attempt is made to connect to the ePJS database.  We don't currently know how many database connections are opened.

2.  provided no access to made to any ePJS-related HealthLocker web pages (eg ePJS clinician sign in, patient's case load, etc.), then no further ePJS database access will be performed.


**Incorrect ePJS database connection details**

1.  attempts are made to connect to the ePJS database.  We don't currently know how many attempts are made per period or for how long this would continue.


If you could confirm that I have your comments down correctly then I think that is fine for now - can you please confirm?  There is now monitoring in place on the ePJS server and we could ask if we can start the live HealthLocker app and have ePJS performance monitored.

**Comment by katbow** [comment]
That's my understanding at the moment.

**Comment by reddog** [comment]
@katbow Thanks for that.

**Comment by reddog** [comment]
SLaM ePJS database team are now seeking permission to allow us to continue testing of the live HealthLocker app.  We will hear back from them.  Until then, the live HealthLocker app should not be brought up.

**Comment by reddog** [comment]
@katbow We've had confirmation that testing of live can continue.

Can you please start the live HealthLocker app and please let me know once done.  SLaM ePJS team will then keep an eye on database server impact.

**Comment by katbow** [comment]
working on building the app now. Will let you know when it's started

**Comment by katbow** [comment]
live has been restarted now 👍

**Comment by reddog** [comment]
In terms of the HealthLocker -> ePJS extract database connection, SLaM are seeing:

- 10 database connections
- each connection is performing the following query once every second

```
SELECT 1
```

I suspect this is a *keep alive* type activity.

The SLaM ePJS team have suggested this is providing about 2-3% extra load on the database server and have asked for *keep alive* activity to be removed.

@katbow can you confirm if the app does have database connection keep alive-type functionality included?  Is it maybe part of the regular library?  If so, can it be turned off?  Are there any issues with turning it off?

**Comment by katyedwards** [comment]
Sorry @katbow SLaM have just asked if we can take the live app down again at 4pm (now) as they are finishing for the day and so can't deal with any drain on ePJS.

**Comment by katbow** [comment]
@reddog disabling keepalive may result in disconnection issues, [see here](https://github.com/elixir-ecto/ecto/issues/195). I am looking for if there are other options for changing the interval, or something else.

@katyedwards OK, I will stop it again now.

**Comment by reddog** [comment]
@katbow Thanks for taking the app down again.  I'll have a look at that keep alive link a bit later.

**Comment by reddog** [comment]
Opened #1090 to continue work on the keep-alive issue.

**Comment by katbow** [comment]
@katyedwards can this be closed in lieu of #1090 since this issue was for the initial request to stop the live site?

**Comment by reddog** [comment]
Closing as working continuing on fix in #1090
