### ISSUE TITLE
Duplicated Day on tracking overview

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1110]
Consecutive days both labelled as Sunday

![screenshot 2017-11-16 14 44 29](https://user-images.githubusercontent.com/24604903/32897130-afe56bdc-cadc-11e7-982b-8f6bd552d454.png)

Sunday 22nd October is correct date!

Client reports it is affecting 3 users minimum
winston@-----.com
nigel@-----.com
desmond@-----.com

Steps taken:
1.	Login to HL
2.	Add relevant information to all the features in “Goals & Tracking”
3.	Go to “Tracker Overview” to review

Seen on Windows 7 desktop - both chrome and IE11

**Comment by katbow** [comment]
Took a small amount of digging, but easy enough fix! Turns out when I was setting the day of the week, I was starting & ending the loop 1 early, so it was setting Saturday to Sunday. It was only happening for Saturday being set incorrectly, and the test was for Friday (and no one was really using it on weekends to catch this). I checked each day now to ensure they were returning the correct day 👍 .

**Comment by katyedwards** [comment]
Fantastic - and in record time!  I'll wait for please test labels once Simon has reviewed!

**Comment by katbow** [comment]
what email will you be using to check this one @katyedwards? I will need to manually add in dates for a Saturday + Sunday for you to test it.

**Comment by katyedwards** [comment]
Good point!  katycrumb@hotmail.com

**Comment by katbow** [comment]
I added sleep data for Sat 18 Nov & Sun 19 Nov for that email. Once it's merged in & deployed you should be able to verify those dates display correctly.

**Comment by katyedwards** [comment]
That's looking good!
