### ISSUE TITLE
Formatting of Coping Strategies

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1116]
Relates to #1074 

If people enter their coping strategies with any formatting, even just putting sentences on subsequent lines, it posts as one continuous paragraph of text

![image](https://user-images.githubusercontent.com/24604903/33328702-8f49756a-d452-11e7-8e22-2ad4dd0b7f3b.png)

![image](https://user-images.githubusercontent.com/24604903/33328747-b40450aa-d452-11e7-9acd-293d7eb709bd.png)

What can we do to allow some basic formatting, but still maintaining security against cross site scripting??

**Comment by katbow** [comment]
For this, I'll be allowing `<p>` tags only. 

@katyedwards I just realised that for this, if the text were entered as it is above, that still wouldn't format to paragraphs actually. It would need to have and extra space between each line. What would you prefer - have a note as part of the instructions to do this, or add in `<ul>` and `<li>` tags as well so that it can format correctly to bullet points without adding the extra space?

**Comment by katyedwards** [comment]
Sorry, being dim this morning.  So how would the bullets display with just the <p> tag?

And just to check my understanding!  We need it to work so the user can just hit the return key and it'll go onto a new line - I think using actual tags will confuse some people.

**Comment by katbow** [comment]
yes, sorry, the user won't input the actual tags. They will just format it a certain way & it will be converted to those tags, which we can allow or disallow. 

If we use just the `<p>`, then it would display the same way it does currently. It wouldn't recognise the bullet points as a paragraph (since they are not separated by a new line). If someone were to input it with a space between every single line like:

```
If I am feeling nervous I can:

- do this

- or this
...etc
```

Then each point would display on a new line.

**Comment by katyedwards** [comment]
Yeah so the effect we want is:
- Bullet one and hit return
- Bullet two and hit return
- Bullet three

and 

- Bullet one and hit return twice

- Bullet two and hit return twice

- Bullet three...

**Comment by katbow** [comment]
haha yeah. It's difficult on github because they have markdown and automatically format the bullet points already.
It would look like
- one and return
- two and return

vs.

<p>- one and return twice</p>

<p>- two and return twice</p>

P.s. I'm leaning to the first one to allow bullet points because it a) looks nicer & b) is more user friendly because they don't need to worry about following a particular set of instructions to get it to look a certain way. It's a bit more intuitive.

**Comment by katyedwards** [comment]
I agree the first one is better for bullet points.

If someone wanted to do 2 'paragraphs' though (just next, not bullets as such), would that work?

**Comment by katbow** [comment]
@katyedwards I input content like this:

![image](https://user-images.githubusercontent.com/1287388/33377187-7aed0076-d508-11e7-88ad-c7226f853601.png)

And this is how it becomes formatted:

![image](https://user-images.githubusercontent.com/1287388/33377207-8dd9de5c-d508-11e7-9da0-de0fb0356853.png)

If I try to input a script like this, which would normally cause a popup to show that says "TEST":
![image](https://user-images.githubusercontent.com/1287388/33377253-b97c83c0-d508-11e7-9225-c8d975871e53.png)

Then it sanitises the output to be this:
![image](https://user-images.githubusercontent.com/1287388/33377316-f77e294e-d508-11e7-8012-bbbf43940442.png)

It deletes out anything beside basic html. So this would also allow for other input types like numbering, headings, etc if someone really wanted without allowing for malicious scripts.

**Comment by katyedwards** [comment]
Great, thanks @katbow let me know when it’s ready to test!

**Comment by katyedwards** [comment]
@katbow sorry - am getting an internal server error when I try to click on coping strategies

**Comment by katbow** [comment]
It seems the dependency wasn't loading in. I have a fix for it, but I can't deploy right now. I am stopping early today so I can try again when I get to better internet, which will hopefully fix the issue. If it is something that requires more delving into though, it may need to wait until next week unfortunately.

**Comment by katyedwards** [comment]
Lovely job - thanks!
