### ISSUE TITLE
Transfer HL Repo into Mindwave Organisation

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1117]

**Comment by iteles** [comment]
@katyedwards Hi Katy! It would be great to hear a little more around the reasoning for this. Would it not make a little more sense for an open source health project to be kept independently of one of our organisations so that people can find it and contribute to it more easily?
Or maybe to an existing open source health community?

**Comment by katyedwards** [comment]
@iteles Happy for this to remain open source, the reasoning was that we should have ownership and full access to our projects.

Have agreed with @katbow that she will 'upgrade' myself and David to be owners of this organisation so we have full access rather than transferring it into the MV organisation at this stage.

**Comment by iteles** [comment]
Totally agree with that @katyedwards and @katbow.
Thanks for clarifying @katyedwards 🎉

**Comment by katbow** [comment]
@katyedwards you & @reddog have been updated to admin & a maintainers 👍

**Comment by katyedwards** [comment]
@katbow I seem to be admin for the HL repo, but not the organisation - can you make us both owners of the organisation so we'll have access to Oxleas etc as well.  Thanks!

**Comment by katbow** [comment]
Oh yes of course! I change you to an owner for that part now

**Comment by katyedwards** [comment]
Lovely, thank you!
