### ISSUE TITLE
Styling of steps displayed on SU goals page (014)

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1132]
- [ ] When a SU clicks on goals (from their toolkit)  They should see the steps they have entered (if any) below the goal title:

![image](https://user-images.githubusercontent.com/24604903/33882871-8589d616-df31-11e7-9395-15f2f9ab363d.png)

Apologies for the dodgy mock up again!

- [x] Goal text should be exactly as it is (bold)

- [x] Steps text should be the same size as the Goal text but not bold

- [x] The spacing should be as it appears on the new goal page, but without the grey entry boxes styling - the steps text should just be on a white background.

- [x] The steps tick boxes aren't tickable on this page, but if a step has been ticked, a tick shows in that box - ideally a grey box, filled in white with a grey tick (different to above) so it doesn't look like you can tick it and confuses users.

- [x] If possible... only display the steps which have been entered (if any), not blank lines with a box but no text.

- [x] If no steps have been entered, no steps or boxes appear.

**Comment by RobStallion** [comment]
@katyedwards. I have been following the steps above and here is what it looks like at the moment...

![image](https://user-images.githubusercontent.com/15571853/33938721-6e2bc266-e000-11e7-940c-a1048dc64be5.png)

The only step from your list above that I cannot complete is to make the boxes grey with a grey tick. The reason for this is because we currently use pngs for these boxes so we would need new png files with the updated colours to allow this work in the same way.

**Comment by katyedwards** [comment]
@RobStallion that will be fine for now - we can always update the styling when there is next proper development.

Is there a reason three is top of the list and is unticked or is that just how you added them?

Just to check - I was expecting they'd be displayed in the same order as they were entered.

I know it's just after 12.30pm but will that one be reviewed by Simon this lunchtime so SLaM can review this afternoon and maybe get deployed to live?

**Comment by RobStallion** [comment]
@katyedwards. Okay then. I will leave the styling as it is now and make a pull request. I'll let you know as soon at it gets the green light so that SLaM can begin reviewing it. 

With regards to the order, I entered them in the order one, two, three but they changed to the order above once I checked the some of the boxes. I think that this is something that can be changed fairly quickly so if you would like to then feel free to open an issue for it and I will take a look so soon as I can.

**Comment by katyedwards** [comment]
Thanks @RobStallion I will add another issue as you suggest.

**Comment by katyedwards** [comment]
Functionally it looks good, but we're going to provide a new svg file for a grey box and grey tick.

Can you let me know the specification for size/format etc you need for the asset.

Thanks!  (not now, this is a note ready for 3rd Jan!)

**Comment by katyedwards** [comment]
@RobStallion can you add specification ASAP here so Jade can get on creating the files for you while you're working on the issue before.  Thanks!

**Comment by RobStallion** [comment]
Hey @katyedwards. I just wanted to confirm that the boxes are png files.

**Comment by katyedwards** [comment]
![unchecked_box](https://user-images.githubusercontent.com/24604903/34517429-e1ab2e52-f072-11e7-8f24-b4502303850b.png)

![checked_box](https://user-images.githubusercontent.com/24604903/34517431-e3338b0c-f072-11e7-9755-d508f9c1059b.png)

Let me know if you have any problems with these.

**Comment by katyedwards** [comment]
LGTM!  Have handed over to client to test and will raise another issue to deploy to live once they have approved it.
