### ISSUE TITLE
Certificate expired on live

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#1136]
![image](https://user-images.githubusercontent.com/1287388/33990370-9f634d6e-e0c2-11e7-916f-56b5cbf1f6e2.png)

@RobStallion I had this before with staging I think. The certificate updated automatically, but was named differently (so nginx was still pointing to the expired certificate).

**Comment by katyedwards** [comment]
FYI the client use GoDaddy for SSL certificates so may decide to deal with this themselves and get it switched over to their own certificates now.

**Comment by reddog** [comment]
Although configured to auto-renew, the certbot was broken on live and staging due to various reasons.

*Live*

Manual renewal gave the following output:

```
root@HL-Prod:/etc/letsencrypt# certbot renew --nginx
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/www.healthlocker.uk.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for www.healthlocker.uk
tls-sni-01 challenge for healthlocker.uk
Cleaning up challenges
nginx: [warn] could not build optimal proxy_headers_hash, you should increase either proxy_headers_hash_max_size: 512 or proxy_headers_hash_bucket_size: 64; ignoring proxy_headers_hash_bucket_size
Attempting to renew cert (www.healthlocker.uk) from /etc/letsencrypt/renewal/www.healthlocker.uk.conf produced an unexpected error: Cannot find a VirtualHost matching domain healthlocker.uk.. Skipping.

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/www.healthlocker.uk/fullchain.pem (failure)
1 renew failure(s), 0 parse failure(s)
```

This *looked* okay since it was renewing the certificate for `www.healthlocker.uk` on the live server.  Checking the CSR showed showed:

```
root@HL-Prod:/etc/letsencrypt/archive/www.healthlocker.uk# openssl req -in /etc/letsencrypt/csr/0000_csr-certbot.pem -text -noout
Certificate Request:
    Data:
        Version: 2 (0x2)
        Subject:
        Subject Public Key Info:
            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    ...
                Exponent: ...
        Attributes:
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:www.healthlocker.uk, DNS:healthlocker.uk
```

Showing that the certificate is for *two* domains and certbot needs to validate both.

The *important part* of the certbot error was:

```
Cannot find a VirtualHost matching domain healthlocker.uk
```

Looking at the nginx config, only the `www.healthlocker.uk` domain was present.  Edited `/etc/nginx/sites-enabled/default` as follows:

```
...
server {
  listen 443 ssl http2 default_server;
  listen [::]:443 ssl http2 default_server;
  server_name www.healthlocker.uk healthlocker.uk;

  ssl on;
...
```

adding in the second server name into the `server_name` setting.

Re-run certbot with `certbot renew --nginx`.

Restarted nginx with `service nginx restart`.  This still failed and the error pointed to a missing/mis-matched private key file.  The `ssl_certificate_key` config value was incorrect.  Further changed the nginx config file at `/etc/nginx/sites-enabled/default` with:

```
...
  # paths to certificate and key provided by Let's Encrypt
  ssl_certificate /etc/letsencrypt/live/staging.healthlocker.uk/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/staging.healthlocker.uk/privkey.pem;
...
```

The `ssl_certificate_key` *was* incorrectly set to `/etc/letsencrypt/archive/staging.healthlocker.uk/privkey1.pem`

Restarted nginx with `service nginx start`.  All fine now and access via a local web browser works as expected.

Final change was to fix up certbot cron job.  Edited `/etc/cron.d/certbot` so that it looked like:

```
# /etc/cron.d/certbot: crontab entries for the certbot package
#
# Upstream recommends attempting renewal twice a day
#
# Eventually, this will be an opportunity to validate certificates
# haven't been revoked, etc.  Renewal will only occur if expiration
# is within 30 days.
SHELL=/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

0 */12 * * * root test -x /usr/bin/certbot -a \! -d /run/systemd/system && perl -e 'sleep int(rand(3600))' && certbot -q renew --pre-hook "service nginx stop" --post-hook "service nginx start" --nginx
```

Added in pre and post hooks and the nginx flag.  Loaded in the change to cron with `service cron reload`.

*Staging*

Very similar to above except that:

1.  CSR lists only one domain name, so no changes to `server_name` in nginx config required:

```
        Requested Extensions:
            X509v3 Subject Alternative Name:
                DNS:staging.healthlocker.uk
```

2.  nginx config file called `/etc/nginx/sites-enabled/healthlocker_staging`

3.  nginx config value for `ssl_certificate_key` was slightly different (pointing to a different archived key), but the fix was the same.

**Comment by reddog** [comment]
# Important Note

The nginx config file at https://github.com/healthlocker/healthlocker/blob/master/nginx.config is currently set up for *staging* only.  Manual changes are required to fix it up for production (or other environments).
