### ISSUE TITLE
Script to restart HL apps when servers are restarted

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1148]
Placeholder - will add more soon!

**Comment by RobStallion** [comment]
I think that we will be able to resolve this issue by putting a script in the crontab that will attempt to start the server every few hours. 

If the server is already running then the command will fail but it not it will start the server.

**Comment by RobStallion** [comment]
Hey @nelsonic. Would you be able to cast you eye over this when you have a moment and just let me know if there is any way of doing this that you know or could point me to. Thanks in advance 👍

**Comment by katyedwards** [comment]
@RobStallion @nelsonic There is a downside to this that if the server was restarted just after the script had run then we would have to wait a few hours before the app would be restarted.  I assume this is a quicker simpler fix though.

Can you also time estimate an option whereby the app would be restarted as soon as the server was restarted so the client can take a view on which option they want to implement.

Thanks!

**Comment by reddog** [comment]
@RobStallion Having the Healthlocker app running as a service would mean:

1. it would fit in to a fairly *standard* way of working/server set up
2. *standard* set up would allow other developers/support to more quickly understand what's happening on the server and get up to speed/fix issues quicker
3. startup/shutdown would be handled automatically
4. there would be no delay (waiting for the next cron job to fire)

There's an example for Ubuntu 16.04 (and 14.04 later on in the article) here:  https://elixirforum.com/t/elixir-apps-as-systemd-services-info-wiki/2400

Is that useful?  Let me know if there's anything else you need on this one.

**Comment by RobStallion** [comment]
Have looked into the solution that @reddog posted above and after reading the link and another [here](https://www.digitalocean.com/community/tutorials/how-to-use-systemctl-to-manage-systemd-services-and-units) I have created a `app_name.service` file at `/lib/systemd/system/. 

Once the file was created I took the server down manually and tried restarting it with the command `systemctl restart app_name.service`. It appeared to have started the application but I am getting an internal server error on the site now.

![image](https://user-images.githubusercontent.com/15571853/35344245-8e0529f2-0124-11e8-8f87-2b46247f9806.png)
(Have been testing on the oxleas test server as it is used less often. Confirmed with @katyedwards beforehand)

When I check the status of the `service` with the command `systemctl status app_name.service` it is giving me the error `** (ArgumentError) cookie store expects conn.secret_key_base to be set`

Looking into what is causing this error

**Comment by RobStallion** [comment]
Current state of the `.service` file. 

```
-----> starting production servers

production node:
[Unit]
Description=Oxleas daemon

[Service]
Type=simple
User=root
Restart=on-failure
Environment=MIX_ENV=prod "PORT=4000"
Environment=LANG=en_US.UTF-8

WorkingDirectory=/home/oxleasadmin/oxleas_adhd/builds/

ExecStart=/usr/local/bin/mix phoenix.server

[Install]
WantedBy=multi-user.target
```

When it is running in `prod` I am getting the error above. I changed `Environment=MIX_ENV=prod "PORT=4000"` to `MIX_ENV=dev` to see if it might log an error but the site seems to work. Was able to create and connect users. Also went through a few pages and everything seemed to be working as expected. There is an error in the console however which does not happen when the site is running normally...
![image](https://user-images.githubusercontent.com/15571853/35346163-6036c2f6-0129-11e8-8cba-50a21f0f4359.png)

Next step, checking to see key differences between `dev` and `prod` config files

**Comment by RobStallion** [comment]
After looking at the `prod.exs` file it looks like the main issue is to with this like 
``` 
secret_key_base: System.get_env("SECRET_KEY_BASE")
```

It seems like the problem could be to do with the files not being able to access the environment variables this way.

**Comment by RobStallion** [comment]
I have managed to get the site working by putting the env variable directly into the `app_name.service` file like so...

![image](https://user-images.githubusercontent.com/15571853/35385492-66f26e3c-01c0-11e8-8302-0a81493ce205.png)

Do now know if this is best practice however. Exploring other possible solutions but will use this solution if I cannot find a better approach.

**Comment by katyedwards** [comment]
`Do now know if this is best practice however. Exploring other possible solutions but will use this solution if I cannot find a better approach.`

@RobStallion is there someone else at dwyl you can check this with to save you a bit of research time?

**Comment by RobStallion** [comment]
After having discussed with various people going to use the approach mentioned above.

**Comment by RobStallion** [comment]
Have added the rest of the env vars needed to run the application to the `.service` file now and the site seems to be working as expected.

Next step is to enable the application to be started on boot. Running to following command 
```
systemctl enable app_name.service
```

**Comment by RobStallion** [comment]
After running the above command I got the following...
```Created symlink from /etc/systemd/system/multi-user.target.wants/oxleas.service to /lib/systemd/system/oxleas.service.```

Everything appears to be working as expected. 

@katyedwards We would need to have the staging server for oxleas rebooted to see if the service restarts automatically

**Comment by katyedwards** [comment]
Thanks, I'll get in touch with SLaM to see when they can do it.  Can you remind me of the specific name for that server to make sure they get the right one!  Thanks @RobStallion

**Comment by RobStallion** [comment]
@katyedwards the name is `Oxleas-HL-Test`

**Comment by RobStallion** [comment]
Server was restarted and the site has come back online and appears to be working as expected.

**Comment by RobStallion** [comment]
@katyedwards Although the servers appear to be up and running as both the staging and live sites are working I cannot `ssh` into either of them. As I cannot get onto the servers I cannot start this issue.

**Comment by RobStallion** [comment]
@katyedwards Would you be able to contact SLaM to inform them of this and could you check if there is anything that they are working on?

**Comment by katyedwards** [comment]
@RobStallion are you getting any particular error etc?

**Comment by RobStallion** [comment]
@katyedwards The exact error is...
`ssh: connect to host ip_address port 22: Operation timed out`

**Comment by katyedwards** [comment]
@RobStallion I haven't heard anything from SLaM, but got a server monitor alert:

HLockerstaging2 started reporting again at 2018-01-31 13:36:47 +0000.

Is it worth you trying to access again?

**Comment by RobStallion** [comment]
@katyedwards. Thanks for letting them know. I have just tried to `ssh` into the server again but I am still getting the same error as [here](https://github.com/healthlocker/healthlocker/issues/1148#issuecomment-361915679)

**Comment by reddog** [comment]
@RobStallion Thanks for doing the startup/shutdown script.  Is this in the repo?

Has installing the daemon starup/shutdown script been included in the documentation?  I guess that the main document for these things is the Oxleas setup doc (which is in turn referenced by the HL setup doc) at https://github.com/healthlocker/oxleas-adhd/blob/master/deployment_and_ssl_doc.md

**Comment by iteles** [comment]
@reddog We won't close this issue without including the relevant documentation.

**Comment by katyedwards** [comment]
@RobStallion Matt has an idea he is going to try... I'll let you know as soon as I know anything more

**Comment by RobStallion** [comment]
Have opened a question [here]( https://stackoverflow.com/questions/48829592/how-to-use-environment-variables-in-a-service-script) on stack overflow asking how to use environment variables in a `.service` file.

**Comment by nelsonic** [comment]
@RobStallion thanks for opening the question. you've _already_ received an answer. (_and I've up-voted_)!

**Comment by katyedwards** [comment]
Confirmation received from SLaM that they are happy for us to restart the staging server as we need - no further permission needed.

**Comment by RobStallion** [comment]
Following steps above to crate and run a script capable of starting healthlocker on a sever reboot on the HL staging2 server.

**Comment by RobStallion** [comment]
I have created the file and run the following commands
```
systemctl start healthlocker.service
systemctl status healthlocker.service
```

Currently getting the following error
```
● healthlocker.service - Healthlocker deamon
   Loaded: loaded (/lib/systemd/system/healthlocker.service; disabled; vendor preset: enabled)
   Active: inactive (dead)

Feb 22 12:34:39 HLockerstaging2 mix[29697]:     (stdlib) erl_eval.erl:229: :erl_eval.expr/5
Feb 22 12:34:39 HLockerstaging2 mix[29697]:     (stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
Feb 22 12:34:39 HLockerstaging2 mix[29697]:     (stdlib) erl_eval.erl:236: :erl_eval.expr/5
Feb 22 12:34:39 HLockerstaging2 systemd[1]: healthlocker.service: Main process exited, code=exited, status=1/FAILURE
Feb 22 12:34:39 HLockerstaging2 systemd[1]: healthlocker.service: Unit entered failed state.
Feb 22 12:34:39 HLockerstaging2 systemd[1]: healthlocker.service: Failed with result 'exit-code'.
Feb 22 12:34:39 HLockerstaging2 systemd[1]: healthlocker.service: Service hold-off time over, scheduling restart.
Feb 22 12:34:39 HLockerstaging2 systemd[1]: Stopped Healthlocker deamon.
Feb 22 12:34:39 HLockerstaging2 systemd[1]: healthlocker.service: Start request repeated too quickly.
Feb 22 12:34:39 HLockerstaging2 systemd[1]: Failed to start Healthlocker deamon.
```

Looking into possible reasons for this

**Comment by RobStallion** [comment]
I am able to access the site using the `.service` file when running in dev mode. Had a similar issue perviously [here](https://github.com/healthlocker/healthlocker/issues/1148#issuecomment-360206010) which leads me to believe it is the same issue regarding environment variables. 

Next step is to check to see if this is the case

**Comment by RobStallion** [comment]
Issue is to do with the environment variables again. Had a question on stack overflow which I linked [here](https://github.com/healthlocker/healthlocker/issues/1148#issuecomment-366262317). Have been trying to use the answer they suggested but have had no luck as of yet. 

Looking into this now. If I cannot use this answer I will go with the solution that was working previously.

**Comment by RobStallion** [comment]
Issue **is** to do with environment variables. I have tried using the answer from [this](https://stackoverflow.com/questions/48829592/how-to-use-environment-variables-in-a-service-script) SO question but I can't seem to get it work. 

Going to try and get it working using the solution in the answer as it would stop us needing to duplicate all the env variables.

**Comment by katyedwards** [comment]
Is this different to the script on HeadScape for some reason? @RobStallion

**Comment by RobStallion** [comment]
@katyedwards it is mostly the same. There are a few differences, mostly the environment variables that are needed to make the application run. I was just trying to implement the solution that was suggested to me in order to save time on creating these files in the future (and to also reduce on duplication) but I am having a few issues with it now. 

Going to just use the same approach for souring `env vars` as I did when creating the oxleas `script`

**Comment by RobStallion** [comment]
I have added the variables and ran `systemctl enable healthlocker`

**Comment by RobStallion** [comment]
Have updated the `healthlocker.service` file so that it now uses the `EnvironementFile="path/to/file"`.

The file that has the list of variables in is now just required into the `healthlocker.server` file. 

As I have proved that this can work the next step is to update the `.profile` so that it no longer uses `export` as this is what was causing the error in the `service` file. 

We will still need to source the variables from the `.profile` and this cannot be done without using the `export` keyword. @nelsonic pointed me to [this SO question](https://stackoverflow.com/questions/19331497/set-environment-variables-from-file) where I found this piece of code 
```
export $(cat .env | xargs)
```

We can take this and update the `.env` in the argument with our `.profile` file (the command will become `export $(cat .profile | xargs)`) and this will work in the command line (have tested this).

Unfortunately we will be unable to fully test that this works until the issues around deployment are resolved. The reason for this is that `edeliver` uses `bash` commands to source the environment variables (can be seen [here](https://github.com/healthlocker/healthlocker/blob/master/.deliver/config#L27-L37)) but as we cannot deploy currently I will not be able to see if the any updates to the `.deliver/config` will work.

**Comment by reddog** [comment]
@RobStallion Thanks for the update.  Sorry I wasn't able to provide input sooner, I wasn't sure where exactly the problem was that you were trying to solve.

Reading further down the chain on Stack Overflow at https://stackoverflow.com/questions/19331497/set-environment-variables-from-file it looks like the initial solution proposed fails in a number of situations, including variable values containing spaces, comment lines, etc.

It's great that none of those conditions aren't present just at the moment, but they could be pitfalls waiting to catch someone out in the future.

For example, try with a file `test-vars.txt` of:

```
foo="some value"
```

and then export with

```
export $(cat test-vars.txt | xargs)
echo $foo
```

This will fail.

There are enhancements that address comments, and spaces, but all add to the complexity.

The answer further down makes use of `set -a` which will cover the error cases above and is very short and simple, see https://stackoverflow.com/questions/19331497/set-environment-variables-from-file#42670496

Reading from https://unix.stackexchange.com/questions/79064/how-to-export-variables-from-a-file#79077 you can make it even more portable by replacing the `source` command with the `.` command.

To test:

```
set -a
. ./test-vars.txt
set +a
bash
echo $foo
exit
```

I enter a sub shell to check the `foo` environment variable in order to *ensure* that it has been `exported` and not just yet.

In my examples, `test-vars.txt` would be replaced with the name of the service environment variables file as specified at `EnvironementFile="path/to/file"`.

**Comment by RobStallion** [comment]
Have updated the `.profile` on the server with the example shown in [this SO answer](https://stackoverflow.com/a/45971167/5512987). 

With the file set up like this, both `edeliver` and the `oxleas.service`, can use the same file to source the `environment variables`. 

This will minimise the chance of error as any new variables will only have to be added in one place. 

Will update the documentation. See #1157

**Comment by RobStallion** [comment]
This still needs to be implemented on the HL staging server. Steps to replicate what has been done can be found in the HL service script documentation, see #1157. 

Although we can access the server to make these changes, as we are unable to deploy the app we would not be able to test fully if the changes have worked or not. That is the reason for holding off at this point in time

**Comment by ghost** [comment]
Implemented and tested on all servers
