### ISSUE TITLE
Write docs for how to write and control oxleas.service script

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#1157]
Write a document for the `.service` files.

Will need to show

- how and where to create the file
- add environment vars
- commands to start, stop and restart the application
- instructions on how to automatically start the application with the file if the server ever restarts

Moved from HeadScape Sprint

**Comment by katyedwards** [comment]
Hi @RobStallion As suggested I asked @reddog to have a look and he has made the following notes... I'm going to move this down the priorities a bit though as getting ssl and the previous work finished/ deployed will be more important today.

Comments on https://github.com/healthlocker/healthlocker/blob/master/healthlocker.service  :

1.  `Description="example app_name daemon"` - probably could have put a description here?!
2.  `WorkingDirectory="the file path to my app"` - guess this isn't needed (as it doesn't have a real value), so it should be deleted - however, see below...

Comments on https://github.com/healthlocker/healthlocker/blob/master/healthlocker_service_script.md :

1.  really doesn't need to include details of how to use a text editor.  Either the document should be directed at someone who it should be assumed does know how to do so, or should include a link to (much more comprehensive, and ready-made) instructions elsewhere on the internet
2.  makes reference to filling in `Description` and `WorkingDirectory`.  `Description` should already be completed, shouldn't it?  There are no details of what to use for `WorkingDirectory` ...
3.  included is *another* list of environment variables that Healthlocker needs.  This is just another list that needs to be maintained (or forgotten about and hence not maintained).  Rather a link to a *single* list of required environment variables should be used, eg see https://github.com/healthlocker/oxleas-adhd/blob/master/deployment_and_ssl_doc.md#add-environment-variables-to-azure

A link to this configuration step should be included in the main deployment document, which happens to be in the Oxleas repo at https://github.com/healthlocker/oxleas-adhd/blob/master/deployment_and_ssl_doc.md


The `healthlocker.service` file should probably have a dependency listed for Postgres (both Healthlocker and Oxleas have their own database that's required, independent of whether or not ePJS is required).  Add the following to the `Unit` section:

```Requires=postgresql.service```

**Comment by iteles** [comment]
@katyedwards A few notes on the points above:
My understanding is that we are providing steps to create a script that can be used in future implementations of the Healthlocker application (beyond Headscape).

On the 3 points on the `md`:
1. This isn't how to use just any text editor. It's `vim` and there are a number of developers who don't use vim. It's easy to get into a tussle with it. Given that there is a very small number of steps, @RobStallion has followed the standard dwyl protocol here and written them in rather than sending people to detailed documentation which would take much longer to read and decipher for something so small. Happy either way but this is how we would usually approach this.
2. The description should match the specific application using the script. We can make it generic but things are much clearer if they aren't - in our case we have `Healthlocker` or `Oxleas` in the description field for the current script. Similarly for `WorkingDirectory`, the file path will be different depending on the application. For example the script is in `lib/systemd/sytem` but the WorkingDirectory for _healthlocker_ is `home/hladmin/healthlocker/buils` - for Oxleas this path would naturally be different 
3. Rob is working through a solution for this in https://github.com/healthlocker/healthlocker/issues/1148#issuecomment-366262317 and if David has any experience in doing this then I'm sure that would be most helpful!

**Comment by katyedwards** [comment]
@iteles have asked @reddog to respond on this particular issue as it's obviously _not_ my area of expertise!

**Comment by reddog** [comment]
Thanks for your reply @iteles.  Just briefly in response to your points:

1.  Details on the commands required to use `vim` to edit a file on the server seem to be not specific to this project.  If instructions on how to us a specific editor are required, would there not be more value in referencing a document (already written, so re-using) where these instructions are shown, or if such a document doesn't already exist, writing a generic one in a place that means that it is more likely to be found and hence re-used?

2.  An example for `WorkingDirectory` would make the documentation more helpful.  A previous acceptance criteria for similar documentation was "in the event of a disaster, can we pick up and run with the document in order to rebuild a server".

3.  With regard to environment variable inclusion in the `.service` file, @nelsonic referenced the answer to @RobStallion's question on Stack Overflow here https://github.com/healthlocker/healthlocker/issues/1148#issuecomment-366275056 which seems like a great solution.  It doesn't seem to have been implemented as yet, see https://github.com/healthlocker/healthlocker/blob/master/healthlocker.service (and no relevant pending pull request)  If an *value-less* environment settings file were created, it could be:
  a.  included in the repo (it'd be value-less)
  b.  used as a check-back tick list to ensure that all environment variables are set
  c.  be a single point of reference of what the app's required environment variables are
  d.  referenced in documentation as to where to look for what the required environment variables are
The *value-less* environment settings file could look like:
```
# this is an value-less environment variables file. Fill with correct values for your environment
setting_1=
setting_2=
# example comment - default setting might work in most cases here
port=5678
# example comment - use PROD or STAGING
env=
```
See https://www.freedesktop.org/software/systemd/man/systemd.exec.html#EnvironmentFile= for further details

**Comment by iteles** [comment]
@reddog Keeping this quick:
1. Yes, agree with you in general on this point and am sure Rob would have done this had there been more than a handful of tiny steps here 👍 
2. Great point, we should do this before we close this issue
3. As you say, this exactly the solution we have been trying to implement but have as yet not been able to (see https://github.com/healthlocker/healthlocker/issues/1148#issuecomment-367741336). The key here is that at the moment there is a large potential for human error because we need to manually add in new env variables.

We'll look to update the docs tomorrow with the latest and hopefully close this issue.

**Comment by reddog** [comment]
Thanks for your reply @iteles.

It might be useful to add some further clarification around your comment:

> The key here is that at the moment there is a large potential for human error because we need to manually add in new env variables.

The solution given in Stack Overflow, and which I referenced above, would seem like fairly standard practice.

Is the `EnvironmentFile` setting not working?  It isn't clear from https://github.com/healthlocker/healthlocker/issues/1148#issuecomment-367741336

Or, are you meaning that you are wanting to establish some form of storing environment variables (securely, and not within the code repo) for all environments (staging and production), *somewhere*, and that these would then be obtained either at server provision time, or on each start of the Healthlocker service?  If you are meaning this, that that's probably a new issue, and isn't really the topic of https://github.com/healthlocker/healthlocker/issues/1148

**Comment by iteles** [comment]
@reddog I mean the solution that was given on SO is definitely what we want to implement in #1148, but at the moment it's not working so we're still in the 'manual' stage

**Comment by RobStallion** [comment]
Have updated the `healthlocker.service` file so that it now uses the `EnvironementFile="path/to/file"`.

The file that has the list of variables in is now just required into the `healthlocker.server file`. 

As I have proved that this can work the next step is to update the `.profile` so that it no longer uses `export` as this is what was causing the error in the `service` file. 

We will still need to source the variables from the `.profile` and this cannot be done without using the `export` keyword. @nelsonic pointed me to [this SO question](https://stackoverflow.com/questions/19331497/set-environment-variables-from-file) where I found this piece of code 
```
export $(cat .env | xargs)
```

We can take this and update the `.env` in the argument with our `.profile` file (the command will become `export $(cat .profile | xargs)`) and this will work in the command line (have tested this).

Unfortunately we will be unable to fully test that this works until the issues around deployment are resolved. The reason for this is that `edeliver` uses `bash` commands to source the environment variables (can be seen [here](https://github.com/healthlocker/healthlocker/blob/master/.deliver/config#L27-L37)) but as we cannot deploy currently I will not be able to see if the any updates to the `.deliver/config` will work.

**Comment by iteles** [comment]
@RobStallion This is great!
I believe this update may be for https://github.com/healthlocker/healthlocker/issues/1148 rather than this issue though as the docs will be finalised once https://github.com/healthlocker/healthlocker/issues/1148 is complete 😊

**Comment by RobStallion** [comment]
Have added the comment to #1148 now. Thanks for spotting that @iteles 👍
