### ISSUE TITLE
Account: Profile: Connect to SLaM account (ePJS)

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#118]
As a user, I can choose to connect my HL account with my SLaM account so that I can connect to my care team and care record.

## Acceptance Criteria 

+ [x] As a user I can tick if I am a SLaM service user
+ [x] If I have ticked that I am a SLaM service user, (just now or some other time in the past, a link to 'Connect with that service user’s SLaM care team' (?) is revealed below.
+ [x] If I click on the (?) I am told how to connect, the benefits and reassured about sharing info.
+ [x] If I click the link, a new page is loaded, I am asked to enter my First name, Last name and Date of Birth and NHS number (?).
+ [x] If I click on the NHS number (?) I am told where to find an NHS number.
+ [ ] Once I have filled in all fields and click connect, the data is matched against records in ePJS.
+ [x] If the data matches, my HL account is successfully connected.
+ [x] If the data does not match, I see an error message and can try again.
+ [x] this flow uses the wording below

<img width="735" alt="screen shot 2017-02-21 at 19 03 31" src="https://cloud.githubusercontent.com/assets/25012688/23180233/9b47afc4-f868-11e6-9492-e558f0e6a22d.png">

## Please use this wording:

[  ]  I am a South London and Maudsley service user.

Connect with my SLaM care team and health record (?) 

(?) To connect you will need to enter your NHS number, First name, Last name and Date of Birth, these details will be matched against your SLaM record - they must match perfectly.
Once your account has been connected you will be able to see the contact details of the SLaM staff you see, view your current care plan, interact with your goals and coping strategies from your care plan, receive recommendations and resources from your care team and more. What you share with your care team, is up to you.

Linked to EPIC: https://github.com/healthlocker/healthlocker/issues/28

**Comment by katbow** [comment]
Looking at this, I think there are quite a few tasks to complete so it may need a bit more splitting up.
I'll write out the parts here and time estimate for those, but I won't add a label yet because it will be over 1 day.

#### Profile page (4hrs)
- [ ] Add field to check or uncheck if it's a SLaM SU
- [ ] Reveal link when to connect with SLaM if box is checked

#### Page for displaying information about connecting with care team (6hrs)
- [ ] Need to display information about how to connect, benefits of connecting, and reassurance about sharing info.
- [ ] Need to know how this is displayed - modals may not be the right answer as there are various extensions, etc which can prevent them from displaying @MollieCourtenay @LauraNevo 
- [ ] Action to render

#### Form for NHS info (1 day)
- [ ] Create form template to display labels & fields
- [ ] Make action to render form
- [ ] Make action to be done after clicking connect

#### Display information about how to find NHS number (6hrs)
- [ ] Need to display info on finding NHS number
- [ ] like the info on connecting with care team, need to know best way to display
- [ ] Action to render

#### Check information input by user with NHS record **ePJS** unknowns before estimation but initial estimate is ~1 day
- [ ] Need to know how we can access the record to check the information. From data dump?
- [ ] What information is sent back during check - success or failure?

#### Display errors if failure (4hrs) **ePJS**
- [ ] Display error to user that information does not match and to try again
- [ ] Depends on how information on failure is sent back

#### Display profile page with additional info from NHS **ePJS** (1 day)
- [ ] Need to update which information can be edited and which cannot
- [ ] Unknown - how to deal with changing address/phone number when it will no longer match with NHS (since it is currently read only)
- [ ] How to include extra fields - dynamically create after connecting account or have in form and keep hidden? or another solution..
