### ISSUE TITLE
Path issue for the nav- how to..

### ISSUE THREAD

**Issue by nogainbar** [healthlocker/healthlocker#189]
I am trying to connect the nav with the assets folder to add the logo. #188 

Tried the normal way -
`src="../../static/assets/HL_logo_white.svg"`
 

as well as the Phoenix way, or what I 'think' the Phoenix way is- 
`
<a class="link dim dib mr3" href="/"><img src="<%= static_path(@conn, "/assets/logo.svg") %>" alt="Healthlocker-logo">
`
cant really get it to work (Kat and I are troubleshooting...)

A general overview of how path works would be very helpful :)

Thank you!

**Comment by tonydaly** [comment]
Hey @nogainbar take a look at using [`img_tag/2`](https://hexdocs.pm/phoenix_html/Phoenix.HTML.Tag.html#img_tag/2), it's a bit easier to work with.

However, I think your issue is actually path issue. What's the local path? It should be something like `web/static/assets/images/logo.svg`. You would then generate the image tag like so: `img_tag("/images/logo.svg")`.

**Comment by nogainbar** [comment]
@tonydaly thats great! thanx! worked perfectly.. 👍
