### ISSUE TITLE
Goals: Mark achieved

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#211]
As a user  I can complete goals and add reflective notes so that I can share my progress and feel a sense of achievement.

+ [x]  As an end user, If I have clicked to edit a goal, I can mark a goal as achieved, when I do I am prompted to add reflective notes and click 'Save'.
+ [x] the date that the goal was marked as achieved is added to the DB
+ [x] the date the goal was achieved is displayed within the goal overview page

Link to #91

![image](https://cloud.githubusercontent.com/assets/25012688/22822233/78eac7cc-ef76-11e6-99c8-a3fe89151e07.png)

**Comment by katbow** [comment]
@MollieCourtenay regarding clicking on "complete" without clicking on edit first: 

I can do this on the 'view goal' page, however the user will still need to click some kind of button if we want to do this without JavaScript.

There are a couple of other ways we can do this. If you want to keep it on the view goal page, `Complete` can be a button that the user clicks instead (and it can change to different wording like "Not completed" if a users marks to complete the goal). The reflection box can show up after the change to the db from clicking the complete button. 

Otherwise it can all be done on the editing page with the checkbox, and when the user clicks Save, then it will update is the goal is complete. However, they would still have to click Save a second time if they did want to add reflection notes.

**Comment by MollieCourtenay** [comment]
@katbow so with option 1 - would the 'Complete' button work similar to 'edit'.
I could see that working nicely - then only need to save once?

**Comment by katbow** [comment]
Yeah, similar to edit. The flow from the user's perspective would be:

* User clicks complete button
* Complete button changes (to "Not Complete"/text of choice) & Reflection/notes section shows up underneath
* User can fill in the notes section and click "Save"
* Reflection section now has content written in by user.

From the db side of things, the "complete" button goes to the db and saves the user's selection, and the page is re-rendered with the new db model which is what can be used to display the reflection/notes section.

**Comment by MollieCourtenay** [comment]
user input - mark goal as achieved. instead of complete.

**Comment by katbow** [comment]
update for the future: I changed the time estimate for this because the database set up is complete now - it's the functionality that needs to be completed now and can be done in a similar way to [marking as important](#214)

**Comment by indiamindwave24** [comment]
[Goal_Achieved-21.svg.zip](https://github.com/healthlocker/healthlocker/files/952299/Goal_Achieved-21.svg.zip)

**Comment by katbow** [comment]
@MollieCourtenay picking this up now so I'm good to go when I get to this one..

The flow changed some since the original diagram for this was added. Since we have moved all editing functionality into edit now, should users only be able to mark goal as complete from the edit view?
Also confirming this is still with a section to mark as achieved, then with reflective notes?

@indiamindwave24 can we also have styles for this? Need to know how this looks in the edit view, how this displays in the goal list/viewing a single goal.

**Comment by MollieCourtenay** [comment]
@katbow have edited the ACs to say mark as achieved is done within Edit screen only.
Would want to keep the option to add reflective notes.

**Comment by MollieCourtenay** [comment]
##Content

'Goal achieved' (instead of Mark as complete)

Reflective notes: (bold)
What went well? What problems did you have, how did you overcome them? How do you feel now?  (italics)

**Comment by indiamindwave24** [comment]
Page without goal completed:

- [ ] Goal icon unselected
- [ ] Delete button under save

<img width="1282" alt="screen shot 2017-05-04 at 1 45 32 pm" src="https://cloud.githubusercontent.com/assets/25007700/25704068/fb8d19ce-30cf-11e7-9775-10d9cd776c32.png">

When Goal icon is selected:

- [ ] Goal icon selected
- [ ] Reflection notes description
- [ ] Free text box for reflection notes


<img width="1280" alt="screen shot 2017-05-04 at 1 45 07 pm" src="https://cloud.githubusercontent.com/assets/25007700/25704067/fb8a6e36-30cf-11e7-9192-6340aaab5e42.png">


[Goal edit icons.zip](https://github.com/healthlocker/healthlocker/files/976143/Goal.edit.icons.zip)

**Comment by indiamindwave24** [comment]
The goal overview page including completed goals would look like this:

<img width="723" alt="screen shot 2017-05-04 at 10 47 43 am" src="https://cloud.githubusercontent.com/assets/25007700/25704648/3d5889d6-30d2-11e7-9910-b13cbf0660e0.png">

**Comment by katbow** [comment]
@MollieCourtenay @indiamindwave24 

In the goal overview page, there is the section that says "Achieved: DD/MM/YYYY" - there isn't anything in the database currently for a date it was achieved on. I can look into how long this might take to implement. Is there an alternative for this for the time being? I would suggest perhaps a heading that says "Achieved goals"

Also, there was a [discussion previously regarding the changing text on star as important](https://github.com/healthlocker/healthlocker/issues/491#issuecomment-297475625). Are you happy for this to stay the same for 'Mark achieved', and confirm an accepted text in that case?

**Comment by MollieCourtenay** [comment]
@katbow A date for achieved in DB - would be good to have an estimate please. 
This would be valuable. 

As for the star as important the text now doesn't change between clicked and unclicked. So can we not do the same for achieved? 

"Mark as achieved "

**Comment by katbow** [comment]
One thing we could do for date achieved is there is an `updated_at` which automatically goes into the DB already which is changed anytime someone edits a goal. We could use this, because presumably goals won't be updated once someone has completed them (and we can see if this is an correct assumption with testing). That would be a reasonably quick implementation (about T1h).

Would you like the title for `Achieved goals` if this is added (and same question for if it is not)? It's there now in https://www.healthlocker.uk/goal if you want to check out how it looks.

I'll change the text to Mark as achieved 🙂

**Comment by MollieCourtenay** [comment]
@katbow  Yes please to the achieved goals title.

And what is the time estimate for adding a new date for achieved in DB?
We will need this in the future anyway so would be good to have an estimate and see if we can get it in.

**Comment by katbow** [comment]
Adding the `date_achieved` would be about T2h.

**Comment by MollieCourtenay** [comment]
@katbow    Shall I make a new issue for it? Or add it to this issue?

**Comment by katbow** [comment]
If it's still the same higher priority than the rest below in this sprint, we can do it here and I will just update the time. If it's not as important as some of the other issues, then yes please open a new one & place it in the order for the sprint.

**Comment by MollieCourtenay** [comment]
@katbow I've added it to the ACS in this issue

**Comment by indiamindwave24** [comment]
<img width="153" alt="screen shot 2017-05-08 at 14 33 49" src="https://cloud.githubusercontent.com/assets/25007700/25806536/6e5ce0aa-33fb-11e7-985c-da7b887439d9.png">

The icon is not centred on the line, can this be amended? @katbow

**Comment by MollieCourtenay** [comment]
@katbow  When the goal is updated and saved, it is possible to redirect the user to the list of goals, rather than the view goal page.

As a user I save, and view, then have to click back to the toolkit, then on goals to view the list - which is not great.

**Comment by indiamindwave24** [comment]
@katbow I marked a goal as achieved yesterday and it appeared in the achieved goal section.

Today, the same goal is no longer marked as achieved? When I click 'mark as achieved' again, the text box is populated with my words that I put in yesterday...?

**Comment by katbow** [comment]
@indiamindwave24 yes, sorry I talked to @MollieCourtenay about this in person & put it in #547 but not here where it matters! Goals that were previously marked as achieved did not have an `achieved_at` date which was causing an error. I reset any goals without an `achieved_at` date to not achieved (but didn't remove any reflection notes), so that when it is marked as achieved again, the date will be there.

If you mark it achieved again, it will appear on the screen as yesterday but with an achieved date 🙂
