### ISSUE TITLE
Goals: Add detail

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#236]
As a user creating a goal, I can add more detailed plans to make the goal feel achievable.

+ [x] As a user creating a new goal or editing an existing goal, I can add steps, each in an individual text box. I am prompted to do so with this wording: '**Steps to take:** List the things you could do to achieve this goal.' 

+ [x] As a user Editing a goal, I can tick off steps that I have taken to achieve my goal, then click save. 

<img width="347" alt="screen shot 2017-04-03 at 17 32 58" src="https://cloud.githubusercontent.com/assets/25012688/24620096/4f165438-1894-11e7-8917-e8080bc68f95.png">

Linked to #91

**User feedback** is that steps to take should be able to be ticked off when they have been achieved. Steps to take is more important that who else could support me. And that this will help make the goal feel more achievable.

**Comment by katbow** [comment]
@MollieCourtenay I'm not seeing a "Who could support you" section in the wireframe for adding a new goal. Is this content that is intended to go in the details section?

**Comment by MollieCourtenay** [comment]
@katbow 

Yes sorry for the confusion, I know it would be clearer if the copy I ask for is in the wires themselves. 

as per #91 copy should be:

**To add a new goal:**

**What do you want to achieve?**
Describe a personal goal.
(Goal is typed in bold text)

**List the steps you could take to achieve it.**
(free text box, user types in regular font, allowing for bullet pointed text on each new line)

**Who could support you?**
(free text box, user types in regular font, allowing for bullet pointed text on each new line)

[ ] Mark as important

(Save)

**Comment by MollieCourtenay** [comment]
insight.

Senior team bought up that goals needs more structure, support user to complete.

Met OT who thinks this is super important - edited the language slightly to be more in line with coaching principles.

SU wants to be able to make a plan for achieving a goal. and would value their clinician adding to their plan.

**Comment by MollieCourtenay** [comment]
@katbow  click to view, tick a step tick box, then save  - makes sense to me. 

As we have a save button - do we need another button?

Mark as important and mark as unimportant when viewing a goal at the moment - doesn't require the user to click save however - can you explain the difference in those interactions, and why we need something else?

**Comment by katbow** [comment]
@MollieCourtenay for mark as important/mark as unimportant those buttons are links which go to an endpoint where the change is made, updated in the database, then it renders the same page again. There is only 2 options for what the data can be - important or not important. If the user clicks on it, then we know the exact change being made.

Because the details would be stored all together in a single spot in the database, there are many combinations of changes, such as ticking only 1 of any details, ticking them all, unticking some etc. We need more input from the user than clicking a single item, so it's best to have the user tick/untick all that they have to change, then clicking to submit that change.

Additionally, because checkboxes are used here, that can't be a link in the same way the important/unimportant buttons can be. So we can't do: tick the box -> go somewhere and save to the database -> come back to the original page.

We have the save button on the edit/add new pages, but not when clicking to view a single goal. We can either add a save button here, or make it editable in only the 'Edit Goal' view.

**Comment by MollieCourtenay** [comment]
@katbow Thanks for explaining. 

I think Edititable tick boxes only when a user has clicked edit.

**Comment by MollieCourtenay** [comment]
<img width="584" alt="screen shot 2017-04-18 at 15 31 06" src="https://cloud.githubusercontent.com/assets/25012688/25136148/145f482c-244c-11e7-894f-5fd925c3ee9d.png">


So as we have just discussed - I cant add steps to an _old_ goal. @katbow
