### ISSUE TITLE
Log in requirements

### ISSUE THREAD

**Issue by LauraNevo** [healthlocker/healthlocker#26]
As a person using HL,
I can log in with my details
so that I can access to additional features.

![log in](https://cloud.githubusercontent.com/assets/3858131/22460534/29c9658a-e79d-11e6-88a9-7bca683a5762.png)

I thought I'd create this issue in order to post my wireframes somewhere. Feel free to edit, add acceptance criteria, etc... :)

**Comment by katbow** [comment]
From end of day discussions with @tonydaly & @nelsonic yesterday: 

Since we are focussing on adding content for all users to see (whether or not they are logged in), the sign up page #12 will be left for now, and users will be loaded in. They will be able to log in through a form like this, and once they are logged in they will be able to add content. 

Non-logged in users will **not** be able to add content, but can *view* non-tailored content.
