### ISSUE TITLE
Session timeout

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#260]
To be discussed with Murat. 
Do we want to implement a XX min time out - seeing as many users use public computers.

What are the other options - encouraging people to log out...

**Comment by MollieCourtenay** [comment]
note: Terms of Service paragraph:


Safety

Whilst Healthlocker sits on a secure platform, and the chance of a data breach is very unlikely, we cannot absolutely guarantee the safety of Healthlocker. As the user you will need to make sure your login in details are kept confidential and not shared with anyone. You will also need to be aware of your surroundings, and we advise you only login to your account when you are in a private space.

**Comment by katyedwards** [comment]
### **Highlighted by PEN Testing - rated LOW**
**Overview:**
The application did not terminate user sessions after a reasonable period of inactivity.
A session was left to idle for over 120 minutes, but remained active and usable.
**Potential Impact if Exploited**
Due to the nature of the information stored within the application, this could pose a
risk since it enables bystanders to glean information contained in the application
profiles.
It should be considered to implement an application ping functionality that
automatically expires sessions after a reasonable period of inactivity. For example 30
minutes.
**Recommendations**
A reasonable inactive session timeout for the application should be implemented on
the system and enforced at the server-side.

**Comment by reddog** [comment]
@katbow Can you please provide a time estimate for this?  If you need to perform some initial research, can you please provide a time estimate for that initial stage instead?

**Comment by katbow** [comment]
@reddog the estimate I've added is for implementation, not research time.

**Comment by reddog** [comment]
@katbow Thanks for that.  Does that mean you think you could complete it today?  If so, seems like it would be great to have a go at it.

**Comment by katbow** [comment]
I may not be able to complete it today - I have to head out at 5:30 which is closer to half that time. I can get a start on it though, if you like.

**Comment by reddog** [comment]
Something half finished it's great.  What would be highest on the list that you could complete?

**Comment by reddog** [comment]
@katbow Was there an another issue that you've taken a look at?

**Comment by katbow** [comment]
What do you mean? Have I looked at any other issues this afternoon?

**Comment by reddog** [comment]
@katbow I mean did you decide to stick with this issue or did you look at another?  https://github.com/healthlocker/healthlocker/issues/260#issuecomment-331475917

**Comment by katbow** [comment]
Oh no, I started on this as it was the only one that had been signed off on to start.

**Comment by reddog** [comment]
@katbow Okay, thanks for that.  I don't know if maybe my previous comment wasn't that clear - thanks for letting me know.

**Comment by katbow** [comment]
Thanks for adding the label @reddog! Slipped my mind since I just got going as soon you confirmed. I am just about to push up my changes for this. I have the session timeout added to expire after 30 minutes of inactivity. However, I need to go through the tests still to ensure everything is all good.

**Comment by reddog** [comment]
@katbow Thanks for this.

Can the session timeout period be added as an environment variable setting?

**Comment by katbow** [comment]
I added the session timeout as an environment variable, but it broke a lot of tests initially. I set the variable on travis now, so that should fix them up.

**Comment by katbow** [comment]
@katyedwards I am in the process of deploying this to staging so it will be ready to test soon. It's set to timeout after 30 minutes of inactivity. So if you are using the app any time in that 30 minutes, it will not timeout. However if you go to the site, then leave it for 30 mins and try to go to a page that requires you to be logged in, then it will redirect you to log in again.

**Comment by katyedwards** [comment]
Thanks, let me know when it is ready to test and I'll take myself off for some lunch!

**Comment by katbow** [comment]
It's deployed to staging now!

**Comment by katyedwards** [comment]
Thanks... will start my test in a mo!

**Comment by katyedwards** [comment]
Staging works... need to wait a bit longer to check live.

**Comment by katyedwards** [comment]
Yes, all good on live as well. Thanks!
