### ISSUE TITLE
Schema for content (tips, stories, general content)

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#36]
#7 #8 #17

All the content will be stored in a `posts` table, containing fields for `date_created`, `content` (containing the title, body of the posts and tags to indicate type of content or categories in the case of tips), and `user_id` (or `created_by`).

The information for the various types of posts will be stored in the content field, and will be accessed & used depending on their formatting:

- Title will be indicated by `#[space]Title` (and/or possibly a blank line under title?) @nelsonic @tonydaly 

- Tags (for tips) and type of post will be indicated by hashtags #. For example, a story will be identified by #story, or a category within tips will be indicated by #connect.

Tips is currently it's own table, and will instead reference and add to the posts table.

**Comment by tonydaly** [comment]
@katbow we shouldn't need to add a `date_created` field as the `timestamps` will already have a `created_at` and `updated_at` columns which we can use (these are pretty standard and are used for other things in the framework e.g. cache expiry).

Also, stick with `user_id` as this is what Ecto will expect. Check out [`belongs_to`](https://hexdocs.pm/ecto/Ecto.Association.BelongsTo.html#content) as this should setup the foreign keys correctly and make the associations so that we can write nicer code e.g. `post.user`
