### ISSUE TITLE
Error message styling throughout

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#360]
+ [x] error notes in HL pink / red. 

+ [x] highlight field where error occurred in pink outline.

**user feedback - observing users not noticing error messages**

link to #87

**Comment by MollieCourtenay** [comment]
<img width="760" alt="screen shot 2017-04-10 at 11 33 16" src="https://cloud.githubusercontent.com/assets/25012688/24857811/83fe6062-1de1-11e7-8854-afb062ceee25.png">


<img width="768" alt="screen shot 2017-04-10 at 11 34 14" src="https://cloud.githubusercontent.com/assets/25012688/24857856/a7bf2914-1de1-11e7-965a-4dbd081170ec.png">


+ [ ] field where error was to be outlined in pink

**Comment by katbow** [comment]
@MollieCourtenay for the first one in the image, do we want to say specifically which field is the problem? 

I thought it would be similar to redirecting to log in when a user tries to sign up with an existing email address - it would indicate the account exists but details are wrong.

**Comment by MollieCourtenay** [comment]
yes sorry not a very clear example. Here I did not enter a password. only email address.

**Comment by katbow** [comment]
Sorry I'm a bit confused 🙈 . I'm still not certain what to do for that first form.

To clarify from my side as well, there is currently no difference on that form between a field being left blank and an incorrect combination - both will just register as an incorrect combo.

If you only want the error outline to show on blank fields (as opposed to when the combination is wrong otherwise) I can do that but will need to make a few extra changes to differentiate between the 2 cases so I'll need to up the time a bit (t4h total).

If you can let me know if you always want the error on the fields (i.e. email doesn't exist = email outlined, email exists but password is wrong = password outlined, etc), or only if a field is left blank, or not at all then I'll get on it today 👍

**Comment by MollieCourtenay** [comment]
@katbow 
Please leave the log in as it is - with one error messages and no fields highlighted.
(sorry I didn't think about the data leakage of highlighting the password field only - as this suggests the email input is attached to a HL account)

Is that clear?

**Comment by katbow** [comment]
yep, got it. Thank you! this should be ready on all other pages then 👍

**Comment by MollieCourtenay** [comment]
+ [ ] password fields cant be blank either.
<img width="765" alt="screen shot 2017-04-12 at 16 03 56" src="https://cloud.githubusercontent.com/assets/25012688/24964632/b48ed504-1f99-11e7-826d-278d63cf84e0.png">

+ [ ] New password and confirm new password cant be blank either.
<img width="780" alt="screen shot 2017-04-12 at 16 08 14" src="https://cloud.githubusercontent.com/assets/25012688/24964858/5171efaa-1f9a-11e7-8fb6-3fe998b9c8eb.png">

**Comment by katbow** [comment]
@MollieCourtenay I saw you made the new issue for the special case #444. Is this one alright to close now?
