### ISSUE TITLE
Read this story - reduce text size and use link styling #370 

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#369]
## Acceptance criteria

+ [x] Read this story link should be the same text size as the content of the story.

+ [x] Read this story link, align to the right, sit above the 'Log in or Sign up to like this!' offer

**Comment by katbow** [comment]
I'm going to up the time on this because the phoenix link that is being used for "Like" is creating a form tag that can't be styled directly. It's taking up the whole width of the screen, so it's pushing down "Read this story".

I'll have to reset the styles for forms, but also make sure this doesn't affect the styling of other forms. I'll put it to T2h in case anything else will need fixing.

**Comment by MollieCourtenay** [comment]
it is also now very close to the See more stories link - which I have added an issue about making it a button #420

**Comment by katbow** [comment]
@MollieCourtenay we can adjust the spacing between see more stories when completing the other issue 🙂

**Comment by MollieCourtenay** [comment]
@katbow 
As per ACs -   'Read' needs to sit above log in / sign up offer - is this also going to be covered off in another issue you refer to?
