### ISSUE TITLE
Fix current warning messages to ensure future warnings are easily caught

### ISSUE THREAD

**Issue by shouston3** [healthlocker/healthlocker#393]
And a few errors when running:
`mix test`
`mix phoenix.server`

(If your not getting that many issues run these commands without the `_build` (`rm -rf _build`))

**Comment by iteles** [comment]
@shouston3 What's the required action here?

**Comment by shouston3** [comment]
Fixing each one would be my solution.

At the moment there are too many to read and so any indication of future bugs or improper syntax is lost

**Comment by iteles** [comment]
👍  A good task for you and @katbow to pair on for half a day tomorrow I reckon (as both of you would benefit from that knowledge) :blush:

**Comment by katbow** [comment]
I got rid of all of these except 2, which are from Bamboo I think. There's also a lot from Bamboo that show up when the app is first compiled (e.g. when getting new dependencies and testing or running
 the server for the first time after that) 🙁 .

![image](https://cloud.githubusercontent.com/assets/1287388/26016869/b95bcd6c-375e-11e7-838b-3d5c7f74bc46.png)

Would be nice if there's a way to get rid of this if anyone has ideas? If we can do that, then we can possibly include in our `aliases` in `mix.exs` this: 

`"compile": "compile --warnings-as-errors"`

which would not let the app compile unless warnings are fixed. I'm not sure if we want to go that far with it, because now it's at least easier to pick up new errors with (most of) the old ones gone. Once it gets merged in I mean 😃 .
