### ISSUE TITLE
Styling and graphics: About page

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#439]
can we improve it please :)

**Comment by katbow** [comment]
see #442 for styling

**Comment by katbow** [comment]
![](https://cloud.githubusercontent.com/assets/25007700/25339786/b86a6556-28fb-11e7-8481-30c08fd40ebc.png)

Clarifying what needs to be done:
- [ ] increase margins (question below for this)
- [ ] Add dark blue line under first section
- [ ] Add & align images (question below)

If the margins are increased, this would only be done on one page. Here's a comparison for how it looks with current margins vs larger margins

![image](https://cloud.githubusercontent.com/assets/1287388/25706019/27787ab8-30d7-11e7-93ed-99f2112ff5d1.png)

![image](https://cloud.githubusercontent.com/assets/1287388/25706111/621782e0-30d7-11e7-8391-6748fd21e0f2.png)

Because the icons are quite long, they fit alongside the text better when the margins are larger (so the text takes up more space vertically), however I wanted to confirm this since it takes away some consistency for this page compared to the rest of the site.

**Comment by indiamindwave24** [comment]
I think we should keep the margins the same for consistency. Can you make the images smaller to fit with this? @katbow

**Comment by katbow** [comment]
![image](https://cloud.githubusercontent.com/assets/1287388/25707714/4c6f8668-30dc-11e7-9f75-dbe752070b10.png)

That's how it looks with the smaller images.

**Comment by MollieCourtenay** [comment]
Looks good! @katbow 

As long as the 'If you are staff at SLaM...' paragraph is at the same distance from the image as the top paragraph 'If you are a south london and maudsley....'

The third para looks further away from its image in the screenshot above.

**Comment by MollieCourtenay** [comment]
@katbow please see my comment above

**Comment by katbow** [comment]
@MollieCourtenay Oh sorry! I lost that in the list of commits. 

Okay in that case there's 2 options. We can increase the space for the first & second, or decrease the space for the third. The third image is wider than the other 2 so there isn't much space between the image & text when the space is decreased for the third to match the first 2.

![decrease space](https://cloud.githubusercontent.com/assets/1287388/25801796/40696434-33e7-11e7-8cb3-de9c88256e74.png)

or

![increase space](https://cloud.githubusercontent.com/assets/1287388/25801832/5f2eaf28-33e7-11e7-8f83-463565e8b041.png)

**Comment by MollieCourtenay** [comment]
@katbow @indiamindwave24 can we not supply the two images with the same with? Just add some white space to the skinny one?

**Comment by indiamindwave24** [comment]
Yes I will do this now @katbow @MollieCourtenay

**Comment by indiamindwave24** [comment]
[new_size_about_page.zip](https://github.com/healthlocker/healthlocker/files/983597/new_size_about_page.zip) @katbow

**Comment by katbow** [comment]
@indiamindwave24 do you want the white space on the left side of the about carers image since it is  right aligned?

**Comment by indiamindwave24** [comment]
oops —
![carer-45](https://cloud.githubusercontent.com/assets/25007700/25811267/92dfd5e0-340a-11e7-9de3-34d1a18a295f.png)
@katbow

**Comment by MollieCourtenay** [comment]
@katbow 
[ ] The links are breaking up the lines of text: 

Healthlocker is a secure platform powered by the
South London and Maudsley Trust
that promote


And


Anyone can
sign up to Healthlocker to explore wellbeing tips and recovery stories and create 


The images are so tiny on mobile. 
Is this the same problem as the homepage tip icons. And therefore does it need a new issue to sort out stacking the icons differently for mobile? 

 It doesn't feel mobile first.

@india please can you consider this more with future layouts.

**Comment by indiamindwave24** [comment]
I suggest we do as suggested for homepage and stack the images above the text (using original images not the aligned ones for yesterday) @katbow
