### ISSUE TITLE
tips and stories: remove sign up and log in from each tip and story

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#447]

**Comment by indiamindwave24** [comment]
![home](https://cloud.githubusercontent.com/assets/25007700/25191964/49b1d12e-2529-11e7-80d0-700c7f0800a9.png)

- [ ] I will send SVG files for each tip category (5 ways to wellbeing) - the content for these sections can be found on this googledoc https://docs.google.com/document/d/1wHQVJp6p3W2_6debDxn8BtbbHwVPQI717csrodYgSnM/edit

- [ ] Each tip category will have an icon and a small icon on each tip (so that when in a list view, it is clear what category they lie in)

- [ ] Please see the signup/login buttons have moved

- [ ] Story image should sit centered with the bookmark icon left aligned

**Comment by katbow** [comment]
@indiamindwave24 I am going to split that info into a separate issue (possibly more) because the original issue here is complete. Have a couple questions on it which I will post in the other issue.
