### ISSUE TITLE
menu: with care team added the Get support is stuck / no space below.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#558]
![img_2334](https://cloud.githubusercontent.com/assets/25012688/25672705/afe67c16-302c-11e7-9572-0e98a8308971.PNG)

**Comment by katbow** [comment]
can you give me device/browser? When I looked at each device I could scroll down and there was space underneath get support.

**Comment by MollieCourtenay** [comment]
@katbow iphone 5 s. safari.
Although there is LOADS of space there now.

**Comment by katbow** [comment]
Oh okay I see what the problem is. The nav bar was set to 100% of the height of the screen. On screens with a lot of content, this creates a lot of extra space, and on screens with not very much content, it gets cut off.

I have a fix where on the top it looks like this (notice it doesn't show the beta bar with the nav open anymore, but I didn't think that would be a problem):

![image](https://cloud.githubusercontent.com/assets/1287388/25697940/d7167f10-30b4-11e7-92a9-579d0108a006.png)

And below the get support there is always a margin like this:

![image](https://cloud.githubusercontent.com/assets/1287388/25697976/fe0e2442-30b4-11e7-99ae-654b7b166358.png)

Does that look alright?

**Comment by MollieCourtenay** [comment]
@katbow, yep

**Comment by MollieCourtenay** [comment]
Ive still got the same problem tried on two different iphone 5s safari.

**Comment by katbow** [comment]
Think that's got it now! The browser display of iphone wasn't showing the bottom menu that's on mobile safari which is the part that was covering it. I doubled the margin from the last time you viewed it 👍
