### ISSUE TITLE
Sleep graph is still too big on desktop sized screens

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#575]
@katbow cant find an issue for this discussed a while back - have I missed it?

At the moment its so big its unreadable.

**Comment by Cleop** [comment]
**New version:** 

![image](https://cloud.githubusercontent.com/assets/16775804/26356071/cba9d0b0-3fc2-11e7-862f-ab62b7110ba1.png)

**iPhone 5:**
<img src="https://cloud.githubusercontent.com/assets/16775804/26356089/da03910a-3fc2-11e7-8a98-93ee59152af8.png" width=200px />

**Comment by iteles** [comment]
@Cleop You weren't there in the conversations this morning but essentially those two sections at the top are clickable to switch between graphs.

This means that they need to be clickable. Please check [the guidelines](https://www.smashingmagazine.com/2012/02/finger-friendly-design-ideal-mobile-touchscreen-target-sizes/) but I remember this being around at least 44px by 44px or so on mobile.
Also worth noting what happens when someone gives their problem tracker a particularly long name?

**Comment by Cleop** [comment]
@RobStallion has had a look into this because it comes from chart js and so I can't style it using css. He hasn't been able to find a way to resize these buttons yet however I can add a bit more margin around the graph so that they would be further from the 'prev', 'next' buttons on mobile and therefore easier to click on.
