### ISSUE TITLE
Ensure: all ok when care team members change (assign to / deassign from caseload)

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#59]
Service users can switch teams during their time with SLaM, e.g. from Inpatient, to Home Treatment, to Community to Discharge. 

Also clinicians can change who they have on their caseload.

+ [x] Each time a SU / Carer logs in - their Care team contacts are up-to-date.

Link to #43

**Comment by LauraNevo** [comment]
This specific notification isn't designed but here is the notification centre:

![notification centre](https://cloud.githubusercontent.com/assets/3858131/23085601/87ce3284-f560-11e6-9998-f72cc001c437.png)

**Comment by iteles** [comment]
We'll need to put some decent thought into this as there are a lot of possible implications here. My biggest concerns are:
+ Messaging
+ Permissions (access to data)

**Comment by katbow** [comment]
There's some details in #796 for what we'll have to do to ensure this is all good 👍

**Comment by katbow** [comment]
One question we had around this is what happens with previous messages. I am not sure if there will ever be a case where a previous clinician will get the same patient again, so the messages should be maintained. 

Otherwise, if we don't want them visible to the new clinician, then we can delete the messages when the clinician is updated.

If we do want to maintain the messages as well, then can you open a separate issue for this please?

Technically to implement this when a clinician is changed, we would need to:
* check the `updated_at` column in clinician_rooms
* get any messages after the matching `inserted_at` date and display those for that room

**Comment by katyedwards** [comment]
Hi @katbow @RobStallion sorry for the delay in updating this... our understanding was:

The messaging is contained in a room which the SU (or carer) has access to and the Care team have access too.

If you leave the care team, that SU & their carers leave your caseload, you leave that room and have no further access to those messages.

If you join a care team, that SU and their carers appear in your caseload and you join their messaging rooms and can view all current and past messages.

If you leave and then rejoin someone's care team, you would lose access to to it all and then regain the access to all current and previous.

Does that make sense?
If so, is that actually correct?!

**Comment by markwilliamfirth** [comment]
@RobStallion to double check status of this issue with @katbow

**Comment by katbow** [comment]
All good now. When a service user goes to their care team section, then it checks if their current clinician in the chat matches their clinician in ePJS. If it does, they go to messaging as usual. If not, the previous clinician is removed from accessing the chat & the be clinician is added. 

Previous messages are retained & visible.

**Comment by katyedwards** [comment]
@MollieCourtenay can you check that makes sense to you and is ok to close the issue.  Thanks!

**Comment by MollieCourtenay** [comment]
don't want to close until this is sorted #934

**Comment by katbow** [comment]
this goes along with #934

**Comment by katyedwards** [comment]
SLaM have confirmed this is working!
