### ISSUE TITLE
Goals and tracking page. Order of the items.

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#689]
Goals  - Coping Strategies
Care Plan Summary
Diary - Problem Tracker
Sleep tracker - Tracking Overview

**Comment by katbow** [comment]
@MollieCourtenay here's how it looks with this layout
![image](https://cloud.githubusercontent.com/assets/1287388/26413118/e0accebe-40a2-11e7-87d8-7fc650b88597.png)

I was wondering if you might like the order rearranged to this instead?
![image](https://cloud.githubusercontent.com/assets/1287388/26413089/c602262c-40a2-11e7-9f51-47865cbdb927.png)

I thought perhaps since the sleep tracker & problem tracker are similar in functionality/display they might be better to pair on the same line. Additionally, the icons mesh together better this way 🙂 . Let me know what you think!

**Comment by MollieCourtenay** [comment]
Seeing it like that and with the height difference with these icons I like the second option. Thanks for checking in @katbow
