### ISSUE TITLE
Expired ssl certificate

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#712]
![image](https://cloud.githubusercontent.com/assets/194400/26455906/704c449e-4163-11e7-87d5-4a330a47f18b.png)

![image](https://cloud.githubusercontent.com/assets/1287388/26454896/4fafc380-4160-11e7-8544-145adef8fd27.png)

Our ssl certificate needs to renewed on heroku. I wasn't sure if we purchased our own at the time or have done automated certificate managment.

**Comment by nelsonic** [comment]
The _reason_ the SSL Certificate was not renewed was because we were _expecting_ the App to be _deployed_ to SLaM IT controlled Microsoft Azure infrastructure with _SLaM_ controlling the SSL Cert for _complete_ ownership of Security.

But ... since we are still waiting for the Production Environment to be set up, 
I will renew the Cert today. 👍

**Comment by nelsonic** [comment]
@katbow please _confirm_ this is now working again. thanks.

**Comment by iteles** [comment]
All working, thanks @nelsonic 🎉
