### ISSUE TITLE
Messaging styling (spacing) fixes

### ISSUE THREAD

**Issue by iteles** [healthlocker/healthlocker#751]
As a user with aesthetic sensitivities, I'd like a couple of aesthetic issues with the messaging section to be fixed so that the screens are not jarring or inconsistent with the rest of the application.

### Acceptance Criteria (2)
+ [x] Line height needs to be brought in line with the rest of the app (it's bigger at the moment)
<img width="751" alt="screen shot 2017-05-30 at 11 45 06" src="https://cloud.githubusercontent.com/assets/4185328/26579954/ff9b430c-452d-11e7-902c-77fef95df701.png">

+ [x] Reduction of padding in the 'Type a message' text box (bring in line with the account fields for example) - this might also be fixed with line height
<img width="823" alt="screen shot 2017-05-30 at 11 45 14" src="https://cloud.githubusercontent.com/assets/4185328/26579991/1dbb0c96-452e-11e7-8d1d-819959e090eb.png">

**Comment by MollieCourtenay** [comment]
@RobStallion we didn't want the height of the input field to reduce. But just the padding above the 'Type a message' wording to decrease.

<img width="932" alt="screen shot 2017-06-01 at 08 51 27" src="https://cloud.githubusercontent.com/assets/25012688/26670003/dca3c2f4-46a7-11e7-950f-e863bbd685a8.png">

**Comment by RobStallion** [comment]
@MollieCourtenay Sorry about that. From what I read in the AC, it sounded like the styling of the message input was meant to look as it does in the Account section which are all styled that way. 

With regards to the way a message that is longer than the width of the input box is displayed, this has always been the case. Adding or removing the padding would not affect this. Changing the input type to a textarea, like we use in diary entry for example, would allow for multiple lines to be entered but then it would also result in the way the code works having to be changed because textareas do not submit with return like the input currently does. This means that there would have to be some work around to resolve this, like a 'send message' button. 

![image](https://cloud.githubusercontent.com/assets/15571853/26688338/3fe7dc50-46ea-11e7-94f4-6e1f15f97d50.png)

**Comment by MollieCourtenay** [comment]
@RobStallion Thanks for explaining this.

At the board meeting just now - there was a discussion around a whether a Send button would be preferable anyway - so it feels like less Whatsapp, in a small way, and perhaps means users are less likely to expect an immediate response...

How bigger job is it to replace with a textarea with Send button?

**Comment by markwilliamfirth** [comment]
Closing, as this issue has been opened here: https://github.com/healthlocker/healthlocker/issues/904
