### ISSUE TITLE
Remove tick box for SLaM user, only show two options to connect as SU / carer

### ISSUE THREAD

**Issue by MollieCourtenay** [healthlocker/healthlocker#773]
If you are service user or family/friend or carer of someone with the South London and Maudsley NHS Foundation Trust, you can:
- Connect with your care team and health record  
- Connect with the care team of someone you care for

**Comment by iteles** [comment]
@katyedwards I'm not sure I understand the requirement here.    
Are these mutually exclusive?

Maybe a screenshot of the checkbox to be removed might help 😊 
This one was still assigned to @MollieCourtenay so not sure it's quite read for 'public consumption' yet.

**Comment by katyedwards** [comment]
I think the aim here was to remove the need for an SU to tick that they are a SLaM user and click update so instead of this:
![screenshot 2017-06-07 12 15 59](https://user-images.githubusercontent.com/24604903/26875772-3dc9d442-4b7b-11e7-8827-b29e99349433.png)

All users would see this

![screenshot 2017-06-07 12 16 20](https://user-images.githubusercontent.com/24604903/26875831-83f9f4a6-4b7b-11e7-9f8f-243ac999553f.png)

- [ ] But without the I am a South London and Maudsley service user tickbox

- [ ] And with this text above the 2 links:

If you are service user or family/friend or carer of someone with the South London and Maudsley NHS Foundation Trust, you can:

- Connect with your care team and health record
- Connect with the care team of someone you care for

Apologies, I don't have any graphicsy software to mock anything up properly  Does that make sense?

**Comment by katbow** [comment]
In case anyone is wondering for the time estimate for this one: It should just be a quick fix, but might be removing the field from the database which updates with that checkbox.

**Comment by katyedwards** [comment]
Sorry @katbow just realised I missed the dreaded SLaM word in there... could you take that out of both links so they read:

Connect with my care team and health record  
Connect with the care team of someone I care for  

As we state the full trust name above, I think that'll be clear enough and they don't want us using the acronym

**Comment by katyedwards** [comment]
Thank you!
