### ISSUE TITLE
IE11 - Problem tracker error message breaking all tracking!

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#794]
Newly created HL account (not connected to SLaM)

I created a “problem” on HL and then tried to access the tracker, which now falls over due to a server error and now my tracking for EVERYTHING does not work. This means that I cannot test sleep tracking either.

![after_creating_a_problem_and_going_to_tracker_wtf](https://user-images.githubusercontent.com/24604903/26871644-cfba51d4-4b6b-11e7-87e5-ea20af1ba23a.PNG)

**Comment by katbow** [comment]
@katyedwards I found the problem with this. 

We started running the notes for sleep data and the problem tracker through a function which converts the markdown to html (so we will see the line breaks in the tracking overview). 

The dependency we are using doesn't account for when there is no data, so it errors. This is the same function we use for posts & tips, but it never came up before since some kind of content is required for those sections. 

I imagine if you made more sleep data/problem tracker without a note, it would start to error regardless if the user is new or not.

Working on the fix now that I identified the problem!

**Comment by katyedwards** [comment]
Great thanks @katbow !

**Comment by katyedwards** [comment]
All ok on Chrome - @pm5k can you check IE and close issue if all ok!

**Comment by katyedwards** [comment]
Sorry @katbow - in continuing my playing, I submitted sleep tracking and problem tracking with no fields completed and when I clicked on tracking overview, got an internal server error.

**Comment by katbow** [comment]
@katyedwards if you go to tracking again for that account, is it still broken? it seems like a different error for that one (which I'm still going to investigate of course as it's causing the same problem!)

**Comment by katbow** [comment]
Got this error. Placing it here for checking it out & finding the problem 

![image](https://user-images.githubusercontent.com/1287388/26973563-0d503f32-4d0f-11e7-8fbc-3f4b642649e0.png)

**Comment by katyedwards** [comment]
I just tried again in my 'personal' unconnected account - katycrumb@hotmail.com and the same thing happened.  Entered no sleep data, then clicked on tracking and got internal server error

**Comment by katyedwards** [comment]
@pm5k can you test this on IE11 too please, then close if all ok.  Thanks!

**Comment by pm5k** [comment]
Entered without notes and all seems good. Did not test with 0 integer values, but assume this was caught anyway, right @katbow?

**Comment by katbow** [comment]
@pm5k yeah, now you can only enter float values. No more 0 integer values.

**Comment by katyedwards** [comment]
Thanks, I've tried logging in and out and entering nothing or 0 and haven't been able to break it this time!
