### ISSUE TITLE
Button for new posts 

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#81]
There's currently no way to go to `/posts/new` unless actually typing it in. Adding a button/link for this when logged in will be more user-friendly.

**Comment by nelsonic** [comment]
@katbow please seek input from @LauraNevo for this. 👍

**Comment by LauraNevo** [comment]
What if we always display new content first? If it appears on the home page as "Latest recovery stories", "Latest events" (or any type of content) and once clicking for more, they would always be ordered from newer to older.

Since users would be able to "bookmark" content #41 I assume it would be good they see new content on home page / resource pages, so they can appreciate the content is new and changing (hopefully!). What are your thoughts on this @katbow ?

**Comment by katbow** [comment]
@LauraNevo I was unclear in my first post, `/posts/new` is for *creating* new content, not viewing it. So having a button after logging in would allow the users to go to the page to post content instead of having to type in the url.

**Comment by LauraNevo** [comment]
Oh sorry. I'm not quite sure what to suggest as I can't visualise it. Maybe we can chat about it tomorrow, unless you want to go for the solution you suggested earlier?

**Comment by MollieCourtenay** [comment]
happy that this button is removed, and users can add new posts via URL.
