### ISSUE TITLE
Sleep Tracking

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#815]
If you go to sleep tracking, leave the entries as 0 and do not fill in any notes, but accidentally click save, it counts this as your entry for the day and it doesn't allow you to go back to enter again

Is that right?  

Is it easy to add a prompt to check that they intended to enter 0 hours of sleep?  Or prevent them from saving without entering *something*

Someone might feasibly have got 0 hours sleep, but in this case I would assume they would enter some notes about it so something would be completed from the 3 fields.

**Comment by katbow** [comment]
I remember this coming up before. Originally there was a prompt that said something like "Enter hours slept" but it was removed because it was too text-heavy. There could be an empty prompt so it looks like this:

![image](https://user-images.githubusercontent.com/1287388/26971420-fd7d2732-4d04-11e7-9f41-e0720cdb903e.png)

then if someone were to hit save without selecting a number (including 0 as an option), they would get an error that hours slept can't be blank.

**Comment by katyedwards** [comment]
That sounds good - if there could be a 'can't be left blank' type prompt please.  Thanks!

**Comment by katbow** [comment]
gotcha. Want this for the other select fields too? In sleep tracking & problem tracking?

**Comment by katyedwards** [comment]
Good idea - best to be consistent and avoid people getting frustrated if they click accidentally click and then can't re-do.  Thanks!

**Comment by katyedwards** [comment]
Thank you!
