### ISSUE TITLE
How to handle users with no care team?

### ISSUE THREAD

**Issue by katbow** [healthlocker/healthlocker#853]
- [x] Update copy as per @MollieCourtenay's comment below

While we were running through the queries for connecting to slam, we noticed that some service users do not have a care team in the database. The user can connect their account, but there are some issues this causes.

* the user cannot disconnect because there is an error in deleting ClinicianRooms. This doesn't get created in the first place as there are no clinicians to add to the room.
* The care team is a rather useless section. There is no one else in the room for them to message, and there are no contact details for them to see.

What would you like to be done in this case? Should they not be allowed to connect in the first place? The functionality is essentially the same as being a non-connected user because of this, so I think it would be a good course of action.

**Comment by katyedwards** [comment]
I would think we'd want them to be able to connect anyway because if a clin gets added to their care team, this would then be populated.

In terms of not being able to disconnect - since no one can see their stuff, there shouldn't be a need to disconnect.  Presumably if they then get connected to a care team they would then be able to disconnect as anyone else.

Do you have any suggestions of the easiest/ quickest way from your perspective?

Could we just display a message saying 'you do not currently have anyone assigned to your care team'?  Would that be troubling for an SU?  Or add 'contact us here for more information' bit too?

Hopefully for now at least this'll be a real edge case as the clins are intended to be the ones leading the rollout so would only suggest it to people in their caseload.

@MollieCourtenay ?

**Comment by MollieCourtenay** [comment]
Yes I would hope this is an edge case especially as we role out the way that nicola has planned. Clinician first. 

However - if the user has been discharged from SLaM - they will still exist on the DB! 

Can we add a bit of text in red at the top? 
(@katbow whilst looking at this you may have noticed the care team menu UI for SUs and Carers has been replaced with that of the clinicians - grey bit. There is an issue in the backlog for this) 

 ## Content

No staff are associated with your account at this time. 

If you are currently receiving support from SLaM, either call your team or email: healthlocker@slam.nhs.uk

**Comment by MollieCourtenay** [comment]
Is this done?

Suggested a small type change - but not a big deal.
No staff are associated with your account at this time.
If you are currently receiving support from SLaM _and would like to use Healthlocker with your care team, speak to your care coordinator_ or email: healthlocker@slam.nhs.uk

**Comment by katyedwards** [comment]
@Cleop I think this has been done, but can you review and push/pull/ commit it (still haven't got the hang of all the right terminology yet!)

**Comment by katyedwards** [comment]
SLaM have tested and working correctly

![image004 1](https://user-images.githubusercontent.com/24604903/29975552-b4163be4-8f2e-11e7-9484-55fbd2b572c7.jpg)
