### ISSUE TITLE
Staging site should be secure HTTPS only

### ISSUE THREAD

**Issue by reddog** [healthlocker/healthlocker#907]
The staging site (all pages) can be accessed at http://staging.healthlocker.uk  It should only be accessible over HTTPS, with any access to HTTP redirected to HTTPS.

Access via HTTPS currently doesn't work at all (ie it's not the case that HTTP *and* HTTPS are currently set up, only HTTP is currently set up).

**Comment by markwilliamfirth** [comment]
Mark and @RobStallion to ask @nelsonic advice on how to resolve this quickly

**Comment by markwilliamfirth** [comment]
To update this issue:

Nelson is currently debugging

- temporarily shutting down app on staging.healthlocker.uk to update configuration
- adding SSL via NGINX proxy on `staging`

**Comment by nelsonic** [comment]
visiting staging.healthlocker.uk gets _automatically_ re-directed to:  https://staging.healthlocker.uk
![image](https://user-images.githubusercontent.com/194400/28154628-b7cb3cfc-67a2-11e7-9d7f-a34ee0225741.png)

_However_ there is a "_content warning_" because an image is still being served over HTTP (_unencrypted_).
And that image is:
![image](https://user-images.githubusercontent.com/194400/28154652-d96060ae-67a2-11e7-95d5-0f444153f094.png)
Which is _not_ available over HTTPS ... 😞 

So until SLaM update their "media" server, (_or we remove this image from the HL homepage_),
we will continue to see the ❗️ in the URL bar in Chrome/FF.

**Comment by nelsonic** [comment]
Google Chrome ***Canary*** is _smart_ enough to realise that the only image that is being served _insecurely_ is on a different domain and informs the user that the Healthlocker app is "Secure":
![image](https://user-images.githubusercontent.com/194400/28154906-0c665cf0-67a4-11e7-8d32-08d216b0e998.png)

Safari just shows the 🔒  icon in the URL Bar:
![image](https://user-images.githubusercontent.com/194400/28154950-36e0b53e-67a4-11e7-9c82-b6c9b0333c27.png)

@reddog please let us know what we should do _next_. (_thanks!_)

**Comment by katyedwards** [comment]
All the SLaM recovery stories and images are on an http site - is there a reason that particular image seems to be causing problems when the others are ok?

**Comment by nelsonic** [comment]
@katyedwards that is the only image that is being requested by HL over **http** (_unencrypted_)

**Comment by reddog** [comment]
@katyedwards Each story has an image and this is always retrieved from SLaM over regular HTTP (see https://staging.healthlocker.uk/posts ).  We need to take that up separately (maybe host the images -
 doesn't sound best, ask SLaM to move to HTTPS - sounds like a big request, something else?).

We've tested access to the site from a number of locations and it always go to HTTPS.  HTTP access has also been redirected to HTTPS.

As such, I think @nelsonic's work on this particular issue is done - thanks.

@katyedwards do you want to close this issue if you're happy with that?

**Comment by katyedwards** [comment]
Yes thanks.  Will create an issue for the backlog around this retrieval of slam images over HTTP so we don't forget about it and can revisit in a future phase.
