### ISSUE TITLE
staging server not up to date with master

### ISSUE THREAD

**Issue by RobStallion** [healthlocker/healthlocker#922]
@nelsonic The staging server seems to be linked to https://github.com/nelsonic/healthlocker which is currently behind HL's version of master. Just wanted to check and see if you were aware of this and if this or if this is meant to be the case?

**Comment by nelsonic** [comment]
@RobStallion the stating server is deployed via `edeliver` from HL's master. 
this is _built_ in: `/home/hladmin/healthlocker`
please _limit_ your editing of `/home/hladmin/hl-app` to a _minimum_.
I changed the `git remote` in `/home/hladmin/hl-app` to `https://github.com/nelsonic/healthlocker.git` to _test_ the `prod.exs` (_configuration file_)
this _can_ be changed back to `git@github.com:healthlocker/healthlocker.git` 
(_in fact I've **already** done this_)

**Comment by RobStallion** [comment]
Thanks for the update @nelsonic. I haven't changed any of the files permanently on hl-app. I only used it as a place to test code before submitting it to be merged into master as I didn't want it being merged in blind.

**Comment by nelsonic** [comment]
@RobStallion developers _really_ should not be making _any_ changes on the `staging` server,
all code should be written on `localhost`, pushed to GitHub, reviewed, merged & auto-deployed.

the _only_ reason we modified code on `staging` during the MS SQL debugging 
was because it would take _weeks_ to do it "blind". 
we need to "phase out" manually modifying _any_ code on the `staging` server ASAP 
and _automate_ deployment (_which is what I'm working on in https://github.com/healthlocker/healthlocker/issues/841 ..._) but it's proving more difficult than expected ... ⌛️

**Comment by RobStallion** [comment]
Ok I get that. No problem, will keep that in mind going forward.
