### ISSUE TITLE
edit 2 Flash messages saying SLaM - connect and disconnect account

### ISSUE THREAD

**Issue by katyedwards** [healthlocker/healthlocker#981]
replace current wording with the following
Connected:
+ [x] Account connected.

Disconnected:
+ [x] Account disconnected from your care team and health record.

**Comment by MollieCourtenay** [comment]
@markwilliamfirth Why am I assigned? I thought we couldn't edit flash messages.

**Comment by markwilliamfirth** [comment]
@MollieCourtenay - @katbow said this one was fine to do (but this one isn't https://github.com/healthlocker/healthlocker/issues/899)

@katbow could you clarify?

**Comment by katbow** [comment]
I thought this one would be okay because the copy change doesn't contain any links & could be found by searching for the current flash message. Links are slightly more tricky because a module needs to be including in for the links to work from there.

Maybe it's better for @RobStallion & I to do them all until there's a chance to show how the flash messages work. Keeps it simple for the time being!

**Comment by katyedwards** [comment]
It was when you connect to your slam account the flash message was coming up
![screenshot 2017-08-21 15 23 09](https://user-images.githubusercontent.com/24604903/29523369-b7a430de-8684-11e7-8974-6764e6e01d26.png)

BUT, this is on the old heroku site though because staging is still down so I can't check if it is on staging as well.  If you can't find it, maybe it has been sorted.

Sorry, that maybe isn't very helpful!
